### ISSUE TITLE
Map secrets to websites and fill OTP with single key stroke

### ISSUE THREAD

**Issue by viranch** [Sneezry/authenticator#101]
This is a feature request.

It will be very convenient if we can map each stored secret with a website domain (eg, https://mail.google.com/* for GMail secret) and when asked for the OTP, pressing the extension button (on the right of location bar) will generate OTP from the secret of the current webpage, find the input field, and fill the generated 6 digit OTP in that field.

This will save a lot of time fiddling around if you have more than a handful secrets to juggle around.

**Comment by RichardBronosky** [comment]
I was going to suggest that each secret could have a `site_pattern` (like Tampermonkey's `@include`) and `css_selector` (like jQuery `$('#TagId')` selector) fields associated with them. If these fields find a match on the current page, clicking the PIN would autofill instead of copying to the clipboard.

So, for AWS, it would be:

    site_pattern = 'https://*.signin.aws.amazon.com/*'
    css_selector = '#mfacode'

I could probably code the matching and filling, by hard coding that in for myself. But I've never worked with extension interfaces. So, doing it so that it could be accepted upstream may be difficult.

**Comment by RichardBronosky** [comment]
This was changed to [working] a few months ago. Is there a branch for this that I could help develop and test on?

**Comment by Sneezry** [comment]
@RichardBronosky Sorry about the delay, work is too busy, will do this in short days.

**Comment by Sneezry** [comment]
@RichardBronosky this feature has been added in 4.18, and the new release will be available in web market in one hour.

To enable domain match, edit your account issue with `::<domain>` in the end, for example, `Gmail::mail.google.com`.

Please let me know if you have any other question.

**Comment by viranch** [comment]
@Sneezry I don't understand how to use this feature or how it works. Can you put out a quick list of steps or something?

**Comment by Sneezry** [comment]
@viranch click the pencil icon to edit account, add `::domain` after every account issuer you would like to match a domain, then click check mark to save. Like this:
![untitled-1](https://cloud.githubusercontent.com/assets/1621293/26510119/4a68e51c-428e-11e7-9733-09ccc82c4a0c.jpg)

**Comment by RichardBronosky** [comment]
I set it to `Amazon Web Services::us-east-1.signin.aws.amazon.com` but I see no changes in behavior. What does this change do?

**Comment by Sneezry** [comment]
@RichardBronosky Could you confirm version of the extension is 4.18?

**Comment by RichardBronosky** [comment]
![screenshot 2017-06-02 10 28 08](https://cloud.githubusercontent.com/assets/13620/26730378/bfb4d0a2-477e-11e7-878e-948bd5c6a2e2.png)
![screenshot 2017-06-02 10 30 43](https://cloud.githubusercontent.com/assets/13620/26730386/c4fba842-477e-11e7-88ab-456019e100a6.png)

**Comment by Sneezry** [comment]
@RichardBronosky It seems OK. Could you confirm if it works on other domain? Try to change the issuer to `::www.amazon.com`, and see if it will be listed on the top when you visit amazon home page. Also, maybe you can open a new issue, our discussion may spam others' mail box.

**Comment by viranch** [comment]
Just putting the entry on top provides little value. User still has to do a lot of mouse actions to get the OTP.

Can the extension auto-copy the OTP to clipboard when there's a domain match without the user having to access the popup?

**Comment by Sneezry** [comment]
That's tooooo dangerous, I won't do that for the user.

**Comment by RichardBronosky** [comment]
There might be confusion about what this feature is supposed to do. I'm expecting an autofill when I get to this page:
![screenshot 2017-06-02 11 54 05](https://cloud.githubusercontent.com/assets/13620/26733892/3af08166-478a-11e7-9229-7a60713768f5.png)

When I get to the login page just before this one, Chrome autofills in my username and password. and I just hit enter. I'm hoping that the plugin can do the same on the MFA page. Is that what you were trying to implement?

**Comment by Sneezry** [comment]
@RichardBronosky No. I just move the matched entry to the top of the popup. This extension is a workaround for people have trouble to use 2FA on a phone. In fact, the extension has already reduced security of 2FA, and I won't make it worse. Security and convenience are contradictory, and we must find a balance.

**Comment by viranch** [comment]
I agree with @RichardBronosky, I too expected this feature to do something automatically. I'd understand if its not a comfortable choice.

**Comment by viranch** [comment]
Forked off into [viranch/chrome-otp](https://github.com/viranch/chrome-otp) for this functionality, if anyone is interested. Not on web store though. Couldn't thank this extension enough for me to patch.
