### ISSUE TITLE
getting just 000s

### ISSUE THREAD

**Issue by JoJa10** [Sneezry/authenticator#110]
2nd code won't change - just stays as all 0000s.  HELP!

**Comment by JoJa10** [comment]
hello - am I going to get a reply to this??

**Comment by Sneezry** [comment]
did it work for that account?

JoJa10 <notifications@github.com>于2017年5月9日 周二上午3:58写道：

**Comment by JoJa10** [comment]
Thank you.  I re0added JoJa10 using the pencil icon.
