### ISSUE TITLE
Bottom OTP's in list get chopped off.

### ISSUE THREAD

**Issue by Bigsy** [Sneezry/authenticator#12]
It might be a combination of the fact I'm on a 4k monitor with 150% default zoom and chromes 800x600 popup limit but I find that having a few OTP forces the bottom ones in the list to get chopped off. 

I have to add a couple of dummy ones in at the bottom to shunt my real ones at the bottom up so I can see them when I scroll.

Also it would be nice if the zoom level/font size could be chosen I can only fit 3 in the popup without scrolling and I have 9 entries.

Thanks for this addon btw its much better than the others I tried.

**Comment by rebornix** [comment]
@Bigsy it would be great if you can provide snapshot as we don't 4k monitor :(

**Comment by multiwebinc** [comment]
This has nothing to do with the 4k monitor and everything to do with the zoom. To set your default zoom, go to chrome://settings > Advanced > Web Content.

Here's 100% zoom:

![100zoom](https://cloud.githubusercontent.com/assets/901732/7397567/8740f70a-ee66-11e4-9597-d6f98fd2070d.png)

Here's 150% zoom:

![150zoom](https://cloud.githubusercontent.com/assets/901732/7397571/8fe0836c-ee66-11e4-8cea-044b2f3524ac.png)

Notice how the scrollbar is at the bottom.

**Comment by rebornix** [comment]
Got your problem. 

Seems this is an known [Chrome issue](https://code.google.com/p/chromium/issues/detail?id=69265), most extensions with a fixed popup window might be broken while users zoom +/-.

**Comment by Sneezry** [comment]
This issue has fixed in version 4.11, please feedback further.

**Comment by Sneezry** [comment]
I have to reopen this issue, and roll back to early version for issue #13...

**Comment by Sneezry** [comment]
I have given back zoom determination to the users. Change scale value in Resize Popup Page menu. For your situation(zoom into 150%), please set scale to 67%(1 / 150%).

This feature has been added in version 4.13 which has been available in web store.

**Comment by Bigsy** [comment]
Wow, great turn around, thanks very much.
