### ISSUE TITLE
warning for new users Do not use it without backup of all data which you input to this app

### ISSUE THREAD

**Issue by kardinal23** [Sneezry/authenticator#121]
warning for new users
dont install the application without writing down the secrets. Sooner or later this application stops working and you would end up without access to accounts!!!!!!!!!!!!!!!!!

**Comment by Sneezry** [comment]
Are you kidding me??? I do have warned! I even warned before installation! Even after installed, I warned every 30 days!

https://github.com/Sneezry/authenticator/issues/119#issuecomment-303598565

**Comment by Sneezry** [comment]
Also, DO NOT SPAM my project issue list! You have posted couple of posts, you even spam my mail box! Remember, this is an OPEN SOURCE project, you use it without paying me anything, I have no responsibility to help you.
