### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by orschiro** [Sneezry/authenticator#137]
Hello @Sneezry,

This is such a cool project!

Is there any chance we get to see this for Firefox?

**Comment by mymindstorm** [comment]
I ported it to Firefox at [mymindstorm/authenticator](https://github.com/mymindstorm/authenticator)

@Sneezry is it ok if I submit this to https://addons.mozilla.org?

**Comment by Sneezry** [comment]
@mymindstorm sure, nice job!

**Comment by mymindstorm** [comment]
[Here's the listing!](https://addons.mozilla.org/en-US/firefox/addon/auth-helper/) I didn't expect it to get approved so fast, so it's a bit bare currently.

**Comment by orschiro** [comment]
Shared it on Reddit. :-)

https://www.reddit.com/r/firefox/comments/7e7n46/authenticator_is_a_very_cool_new_addon_for_2/
