### ISSUE TITLE
AUTHENTICATOR codes not working!

### ISSUE THREAD

**Issue by theblendedmilk** [Sneezry/authenticator#142]
Hello, 

I'm having big issue with my Authenticator downloaded on Google Store (chrome extension)
The extension was working fine for months but now i'm facing a huge problem with the generated codes.
Indeed, these codes are not working! Third party websites systems say that the codes i'm copy/pasting are wrong

I tried to remove and link again the Authenticator to the websites but still no way for me to enter my accounts!
Please help me fix this issue which is going on since few days

Thanks in advance

**Comment by Sneezry** [comment]
Please double check if your clock time is correct

**Comment by theblendedmilk** [comment]
The time is correct. I have been using the Authenticator for a year now and everything was great so far
I have resync, make sure the time is correct, disconnected reconnected and nothing is working
Generated codes are not accepted by third party websites!

**Comment by theblendedmilk** [comment]
Hello, can i have an answer please? My accounts are blocked because of this issue!!!

**Comment by theblendedmilk** [comment]
HELLO????

**Comment by Sneezry** [comment]
Could you please confirm if your mobile app works with the secret? You can get QR code to import to your mobile app. You can learn how to do it here: https://github.com/Sneezry/authenticator/wiki/Introduction

**Comment by theblendedmilk** [comment]
OK PROBLEM FIXED! THANK YOU FOR YOUR HELP

**Comment by theblendedmilk** [comment]
the problem is solved

thanks for your assistance

2017-08-10 12:15 GMT+08:00 Zhe Li <notifications@github.com>:

**Comment by Sneezry** [comment]
Great!

theblendedmilk <notifications@github.com>于2017年8月10日 周四下午5:27写道：
