### ISSUE TITLE
Authenticator 

### ISSUE THREAD

**Issue by shaukat18** [Sneezry/authenticator#15]
code not showing plz solve my problem

**Comment by Sneezry** [comment]
Hi, please provide more information. What can you see in Export / Import box? Is it only {}?

**Comment by shaukat18** [comment]
just
()

**Comment by shaukat18** [comment]
i have account on mytrafficvalue.com i'm so worry plz help me

**Comment by shaukat18** [comment]
yes only ()

**Comment by Sneezry** [comment]
OK, I still need more information. {} means your data is not in the computer you are using. Do you use a new computer? Did the extension work well? Have you logged in your Google account in Chrome?

**Comment by shaukat18** [comment]
i was just trying to check authenticator. 1st i go to security and than i go to phasphras and type password after that code not showing. and my gmail account login.

**Comment by Sneezry** [comment]
Do you mean you can see the code before you set a new password in security menu?

**Comment by shaukat18** [comment]
yesssss

**Comment by shaukat18** [comment]
i have account on https://www.mytrafficvalue.com/login.html

**Comment by shaukat18** [comment]
![image](https://cloud.githubusercontent.com/assets/12458889/7652933/0ac7df5a-fb2b-11e4-8d5e-74c59310110f.png)

**Comment by shaukat18** [comment]
shaukat.ullah18@gmail.com this is my gmail id plz check and solve my problem

**Comment by Sneezry** [comment]
Hi shaukat, I understand your feeling, however, I do not have your data, your data is never sent to anyone except Google if you have logged in your Google account. Did you remember the version of the extension when you install it or when did you installed it? Can you see the security menu when you installed it first time?

**Comment by shaukat18** [comment]
i install today. and after create password code not showing so i delete extension and again install

**Comment by shaukat18** [comment]
version 4.14

**Comment by shaukat18** [comment]
![image](https://cloud.githubusercontent.com/assets/12458889/7653131/0134f0a2-fb2d-11e4-89b9-773efab30f78.png)

**Comment by shaukat18** [comment]
now see i'm on big problem. how i login my account on mytrafficvalue.com

**Comment by Sneezry** [comment]
I have rechecked the code, Authenticator handles data removing very carefully, data can not be removed when be encrypted. Data only can be removed(including Google's server) under these 3 situations:

1, Update from extension under version 4.3
2, Remove it manually
3, Uninstall the extension

**Comment by shaukat18** [comment]
so now tell me at this time what i should do?

**Comment by Sneezry** [comment]
I'm very sorry about that, shaukat, I hope you have backed up your secret, and I guess you have seen the caution we give in the install page: backup your secret, don't wait until it's too late.

To solve your problem, please try to contact with mytrafficvalue.com, that's beyond my ability, sorry again.

**Comment by shaukat18** [comment]
how i backup extension?

**Comment by shaukat18** [comment]
you mean no chance here?

**Comment by Sneezry** [comment]
I'm afraid so. The website should give you a long code, and tell you to backup it preventing yourself locked outside your account.

**Comment by shaukat18** [comment]
which website give me long code?

**Comment by Sneezry** [comment]
mytrafficvalue.com

**Comment by shaukat18** [comment]
you mean mytrafficvalue.com have secret code?

**Comment by shaukat18** [comment]
so next time this is the very important to save this html code on notpad? 
![image](https://cloud.githubusercontent.com/assets/12458889/7653522/ba79f880-fb2f-11e4-86e8-73936887c4bc.png)

**Comment by Sneezry** [comment]
Sure, they calculate your code with your secret code, and compare it with the code you entered, if they are the same, you are authored.

Every website stores users' secret code in their database.

You should backup your secret code, but not the source code in export box.

![](https://cloud.githubusercontent.com/assets/1621293/7653575/53590d48-fb49-11e4-99e6-d37a3c0e6c45.png)

See the red box? That's where your secret code should be.

**Comment by shaukat18** [comment]
if i know this secret code than my problem should solved?

**Comment by Sneezry** [comment]
Yup

**Comment by shaukat18** [comment]
hmmm so you know any recovery software to recover this secret code?

**Comment by shaukat18** [comment]
mtv solved my problem
now i want the pin code automaticaly change in just 3 seconds. how i set this ?

**Comment by Sneezry** [comment]
I'm happy to know your problem has been solved :-)

You can not change update frequency of the code, totp is a public algorithm, you may get more details on http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm

**Comment by shaukat18** [comment]
if someone hack my id
so this is very important pin code change in just 3 seconds
so this setting not available?

**Comment by Sneezry** [comment]
No, that is not available.

You must have the same update frequency with mtv, or you can not be authed correctly, and the frequency is just 30 secs.

**Comment by iinterval** [comment]
i have same problem it mytraficvalue how can do this solve problem shaukat18

**Comment by shaukat18** [comment]
don't uninstall authenticator and don't click on this minus
![image](https://cloud.githubusercontent.com/assets/12458889/7667156/de1f87a8-fc17-11e4-82cf-c5c124415a63.png)
if you do this so your data gone and code not showing
so this is very important save secret code
anyway you should contact with mytrafficvalue slosumo will remove 2 factor login

**Comment by shaukat18** [comment]
next time save this code it's very important

![image](https://cloud.githubusercontent.com/assets/12458889/7667170/4fc35934-fc18-11e4-9fbd-45851daa8baf.png)

**Comment by iinterval** [comment]
Thank you for informtion i will contact  mytrafficvalue slosumo

Date: Sat, 16 May 2015 10:08:29 -0700

**Comment by iinterval** [comment]
hi shaukat18 i am send it Support ticket mytrafficvalue slosumo how much time to solve my problem
