### ISSUE TITLE
what is passphrase and how to use

### ISSUE THREAD

**Issue by shaukat18** [Sneezry/authenticator#16]
Hi Sneezry,
            I want to kow what is phassphrase and how to use this plz guide me in detail or screen shoots

**Comment by Sneezry** [comment]
When you open export box, you'll see you secret code if you do not set a passphrase, so does any one who uses or hacks your computer. Besides, when you log in your Google account, your secret code will be shared with Google in plain text. However, if you set a passphrase, all your secret codes are encrypted, and no one would know what it is except they know this passphrase.
