### ISSUE TITLE
Can't sync time with google

### ISSUE THREAD

**Issue by feldim2425** [Sneezry/authenticator#17]
I can't sync the time with google. If i click the button it says "Failure."

System details:
Authenticator Version: 4.14
Google Chrome Version 41.0.2272.101 (64-bit)
System Ubuntu 14.04

**Comment by Sneezry** [comment]
Hi, can you open www.google.com in your browser?

**Comment by feldim2425** [comment]
Yes, but it's automatically redirect to www.google.at .

**Comment by Sneezry** [comment]
Hi, how about https://www.google.com/generate_204 , is this url automatically redirected as well?

**Comment by feldim2425** [comment]
No

**Comment by multiwebinc** [comment]
I have a feeling that it's a permissions problem that is causing this because of the redirect. What if you change the time sync URL to google.com/ncr to prevent redirects?

**Comment by Sneezry** [comment]
@multiwebinc changing to google.com/ncr may be not a good idea, cause it may change user's default page of Google. I have changed the url to google.com/generate_204, the url will not be redirected, and it won't change user's settings. I'm waiting for further feedback for this change.

**Comment by feldim2425** [comment]
I have downloaded and installed the new Code and now the Clock Sync works.

**Comment by Sneezry** [comment]
@feldim2425 thank you for your feedback, new version will be pushed to web store shortly.

**Comment by Sneezry** [comment]
4.15 now is available in web store.
