### ISSUE TITLE
How to import data from Chrome extension to smartphone app?

### ISSUE THREAD

**Issue by heihachi88** [Sneezry/authenticator#172]
Is it possible to use multiple devices for Google Authenticator? Currently i am using it mainly on Chrome, but sometimes i need it on my smartphone (iOS). How can i copy the keys and use them on my smartphone?

**Comment by Sneezry** [comment]
please see here: https://github.com/Sneezry/authenticator/issues/69

**Comment by heihachi88** [comment]
Thank you... Didn't noticed it 👍
