### ISSUE TITLE
Pin not matched

### ISSUE THREAD

**Issue by AliSusanto** [Sneezry/authenticator#18]
Hello...

I installed Google authenticator in my PC. I used OS WIndows 8 and my google chrome browser version is Version 43.0.2357.130 m. 

I tried many times using both QR code capture or manual entry, but every time i tried to insert the pin, the statement keeps telling me that the pin is not matched. 

Ps : I tried using my account in my friends Laptop using the same google authenticator but running in Windows 7 and It runs perfectly. So I guess the trouble is on my laptop. 

Please help me solve this issue.

Best Regards,

Ali Susanto

**Comment by AliSusanto** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/13089964/8398002/b86e6be8-1d94-11e5-80bc-bbc34e5a0df5.jpg)

This is my screenshot... thanks

**Comment by Sneezry** [comment]
Please check your system clock, it is probably because your local time is incorrect.

**Comment by AliSusanto** [comment]
Hello...

I already double check my time setting and nothing seems to go wrong.

Please help and give further assistance. thanks

**Comment by AliSusanto** [comment]
Hello.... I tried to sync my time with internet based time and the problem is solved.

Thanks so much
