### ISSUE TITLE
Clarify use cases for import/export in wiki

### ISSUE THREAD

**Issue by darcyparker** [Sneezry/authenticator#20]
See https://github.com/Sneezry/authenticator/wiki/Introduction

I am a new user of 2 step verification and in the process of choosing different time based authenticator apps for different devices.  So far I think this project (authenticator) is promising because it is very convenient to copy the number to the clipboard compared to reading my phone and typing the number in manually and on most of my devices Chrome Extensions are available and in the case of my chromebook it seems to be the best option.  But I think there are cases when I want to use an app from my phone which doesn't support Google Chrome Extensions and I may not have a computer with Chrome available.  For example, I may use Google Authenticator app.

Is the import/export just for backing up authenticator? Or is it a neutral format that I can import into other authenticator tools like the Google Authenticator app?

If it is not a neutral format, how do people login into sites like http://github.com from devices that don't have the authenticator they used when they setup the Two-factor authentication?

**Comment by darcyparker** [comment]
It might be helpful to document the JSON format of the export too... 

For example, I have one key that looks something like this: (I replaced the hexstrings...)

```json
{
  "someHexString_Length32": {
    "account": "github.com/someUser",
    "encrypted": true,
    "index": 0,
    "issuer": "GitHub",
    "secret": "someHexString_Length64",
    "type": "totp"
  }
}
```

If I go into Google Authenticator and do a `manual entry`, which properties above map to the `Account` and `Key` Google Authenticator asks for.   I am assuming the account is simply `github.com/someUser` and that it doesn't have to be an email. Google shows the key as 16 characters... so I am not sure what I should type in.

As well, I am assuming the export is encrypted... so I need to know how to decrypt it for the purposes of adding the account/key to Google Authenticator.

**Comment by Sneezry** [comment]
Hi @darcyparker , to add secret to other apps, you may click the qr icon on the top left corner of every code box (the qr icon is hidden before you move mouse over it), and the qr code of the secret is shown, you may use your smart phone or something else to scan it. You may also find your secret in export box, but it's not recommended. To decrypt your secret, you need to remove your password, after you remove your password, you may find your secret decrypted. To remove your password, just click update button without entering any words. In the code about you post, the someHexString_Length64 is the encrypted secret.

**Comment by darcyparker** [comment]
@Sneezry - nice. That is a great solution.  I didn't notice the QR icon because you have to hover over it to see it.

I now see this documented in the wiki... but it wasn't obvious to me. Do you mind if I add an entry to the wiki to clarify this?

**Comment by Sneezry** [comment]
@darcyparker Sure, thanks :-P

**Comment by Sneezry** [comment]
@darcyparker No of course, thanks :-P

**Comment by darcyparker** [comment]
Done: https://github.com/Sneezry/authenticator/wiki/Introduction#share-account-with-another-authenticator-app

If you like this, please close the ticket.

It may also be good to add the intended use case for the import/export. I am assuming it is just for backups?

**Comment by Sneezry** [comment]
@darcyparker in fact, export / import is for sync, as you know, Google service is hard to use in China ;-P
