### ISSUE TITLE
Cross-computer issues....

### ISSUE THREAD

**Issue by plasmageek** [Sneezry/authenticator#22]
So maybe this isn't meant to be used this way, but when google syncs between computers, it pulls up my authenticator and *claims* to have the same authenticator codes as the source computer they originated on. However, the codes do not match and are actually incorrect. I'm also unsure if removing them from one PC browser version of Chrome will then cause Chrome to lose that data between all of my computers, so this is a bit of an issue?

Thanks!

**Comment by Sneezry** [comment]
I will follow your issue in #23, so this issue is closed.
