### ISSUE TITLE
Easier method to contribute translations

### ISSUE THREAD

**Issue by mymindstorm** [Sneezry/authenticator#220]
Hi @Sneezry! I maintain the Firefox version of your add-on, and I wanted to see if you are interested in providing an easier way for people like @igorrhamon (#195) to contribute translations to this project. 

I got an [instance of Crowdin](https://crowdin.com/project/authenticator-firefox) approved for open source use, so if you wanted to we could link both versions of the extension to Crowdin and add a translate button to the extension. That way both Chrome and Firefox users could easily help translate the extension into other languages. 

Here's what it looks like in the Firefox version, if you are ok with it I'll submit a pull request here with the same changes and give you administrator access to the Crowdin instance. 

![image](https://user-images.githubusercontent.com/27789806/35479986-e60a8424-03c9-11e8-95e3-594c6117fd96.png)

**Comment by Sneezry** [comment]
Hi @mymindstorm , thank you very much about your suggestion!

I must say, code quality of the extension is tooooo poor currently, the extension was written when I was in school, and I should re-write the extension hundreds of days ago. However, work first.

So I do not think it's a good idea to contribute to the current code (it's really a piece of sh**, my bad).

Please give me some time to re-write the entire project with Vue.js and TypeScript (or just JavaScript if others don't like TS).

Thanks again!

**Comment by mymindstorm** [comment]
While the code qualtiy may not be the best, it's the best open source extension that does this out there imo. Even if it should be rewritten I think that it's still valuable to collect this data now so that you can reuse it later.

All Crowdin really does in our case is auto generate messages.json files, so it shouldn't interfere with any code refactoring  (as long as you still use i10n) since you separated the strings in the first place. Even if you move to a different localization API Crowdin should be able to convert between formats easily.

The only thing this would really add is that button, a line of js doing localization work, and a string in messages.json. I don't see how much of anything will suffer from this, so why not add it?

**Comment by Sneezry** [comment]
Yeah, then let's add it into the menu, and I will release a new version to the Chrome Store!

Waiting for your PR ;-)

**Comment by mymindstorm** [comment]
The diffs a bit weird for some reason but #221 is open

**Comment by Sneezry** [comment]
Maybe line endings issue. But it's okay, I have merged that PR.

**Comment by mymindstorm** [comment]
Shoot, I just noticed that I used browser instead of chrome by accident.

**Comment by mymindstorm** [comment]
@Sneezry see #222, I got too used to Firefox webextensions and did a stupid

**Comment by mymindstorm** [comment]
All hell has broken loose, the bug reports are starting to come in.

**Comment by mymindstorm** [comment]
"I don't see how much of anything will suffer from this, so why not add it?"

**Comment by Sneezry** [comment]
Thanks for your update, it is not your fault, I should test it before new release, that's my bad.

It should be okay now, the hotfix is available in the market now.

Take it easy ;-)

**Comment by mymindstorm** [comment]
Again so sorry for causing you so much trouble because I didn't test either. I can say that I definitely learned a valuable lesson today, though.

**Comment by Sneezry** [comment]
@mymindstorm let's make the extension better! I cannot imagine so many users care about this extension!

**Comment by mymindstorm** [comment]
@Sneezry I'm going to submit more prs later with a few changes I made in the Firefox version that you will probably like

**Comment by Sneezry** [comment]
@mymindstorm Cool! Waiting for your PR!
