### ISSUE TITLE
Authenticator BROKEN

### ISSUE THREAD

**Issue by adsactly** [Sneezry/authenticator#223]
I shut my PC off last night and now when I try to use the Authenticator everything is showing up blank I can't even access the Settings or Add or Remove Codes and No Codes are Showing!

Please Help this is an Emergency.

**Comment by adsactly** [comment]
document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');

**Comment by ThePlenkov** [comment]
i confirm

**Comment by mymindstorm** [comment]
Sorry, that was all my fault.; I made a small typo and screwed everything up, and noticed it literally minutes after it got pushed. A fix should be out as soon as @Sneezry is able to merge my pr

**Comment by mymindstorm** [comment]
As a temporary work around you could try disabling or removing authenticator and loading an older version (4.18)  from an archive. Some googling was able to find this: https://crx.dam.io/ext/bhghoamapcdpbohphigoooaddinpkbai.html

**Comment by ThePlenkov** [comment]
Hopefully your code had a check for WebKit so in Firefox it works stable even now

**Comment by mymindstorm** [comment]
@ThePlenkov what I pushed was pretty much the same as [this commit](https://github.com/mymindstorm/authenticator/commit/b9bdd4c4bebb0d1194b2a1abe19e6498c7e79cb6) which is sort of the problem. Firefox uses `browser.i18n` and Chrome uses `chrome.i18n` and in my groggy morning state I forgot to change that. Though the Firefox version is unaffected and has a separate repo at [mymindstorm/authenticator](https://github.com/mymindstorm/authenticator)

**Comment by adsactly** [comment]
yeah well now nothing is showing we tried going back the Version 4.18 and there is Codes Imported. Its good thing we have a backup but its from a LONG time ago. We really hope you can fix this issue because this is very bad we have several QRCodes we can't access now :(

**Comment by mymindstorm** [comment]
@adsactly no data has been lost, it's just crashing and isn't showing the codes. After another update is pushed they will be back.

**Comment by adsactly** [comment]
OK We hope so because not even the older version is showing any codes.

**Comment by adsactly** [comment]
What exactly did you even update in the first place? Everything was working perfectly fine did you guys add a translation feature or something?

**Comment by mymindstorm** [comment]
A button in-between the feedback and source code buttons that would link to[ here  ](https://crowdin.com/project/authenticator-firefox)to make it easier for people to contribute translations.

**Comment by Saurabh995** [comment]
Hi, is there any way I can access the qr codes.. as I am unable to login to various sites.

**Comment by mymindstorm** [comment]
@Saurabh995 Not currently, I made a mistake and broke it by accident. Update with fix coming soon.

**Comment by wrath1** [comment]
Just made an account for this very reason im glad I found answers. btw, it's showing blank for everyone correct?

**Comment by Saurabh995** [comment]
Isn't any cache locally maintained for all the added qr codes?

**Comment by mymindstorm** [comment]
@Saurabh995 this issue isn't with storage and it hasn't been touched.

**Comment by zetb612** [comment]
How long does it take to fix the error?

**Comment by john19991** [comment]
It was working so well till yesterday, and boom all of a sudden today lol....Hope its fixed soon,

**Comment by Saurabh995** [comment]
@mymindstorm What I am saying is that ..aren't the secret keys stored locally in my chrome extension data??

**Comment by mymindstorm** [comment]
Probably, they are stored using `chrome.storage.sync`. The issue here is that the script that causes codes to load is crashing.

**Comment by bmg177** [comment]
sigh, Im an idiot for not having a recent backup I guess although Ive never had an issue like this in many years. Locked out of some very important things I need to access right now. How does this happen? 24 hours MINIMUM for a fix?

**Comment by john19991** [comment]
Had some important activities to do this morning, the deadline of which expires in the next 10 min.  All this happens because of a stupid mistake by one of the contributors...Damn, I cant wait for 24 more hours Please fix this quick

**Comment by bmg177** [comment]
Same here. Really bad timing. To say Im upset right now is an understatement

**Comment by mymindstorm** [comment]
No one should be relying on this as their only method to get two factor codes. If any of you have a backup you can load an older version of the extension and restore from your backup, and you should be able to use it.

**Comment by bmg177** [comment]
Yes its my fault for not being prepared for this. I cannot locate my backup at this time. Took it for granted because Ive never had a problem for many years. Is there anything else I can do? What is this chrome.storage.sync you speak of? Pardon me, Im not familiar with this kind of stuff

**Comment by bmg177** [comment]
'I don't really know how long it will take, probably somewhere between 12-24 hours plus the time it take for the extension to update"

Is there a file I can update or anything I can do on my end that will speed up this process?

**Comment by john19991** [comment]
@mymindstorm  Alright, fair enough. Where do I get the older version of the extension?  I was unable to find it. I need it for chrome desktop

**Comment by mymindstorm** [comment]
Sorry, but there isn't really much anybody can do but wait. If I could do something to stop this fire I already would have.

**Comment by mymindstorm** [comment]
Here is an archive I found: https://crx.dam.io/ext/bhghoamapcdpbohphigoooaddinpkbai.html

Use version 4.18

Go to chrome://extensions and drag the zip you download into the page after disabling the new version, the import a backup using the menu

**Comment by tepidhowl** [comment]
also you can copy Extenstions/bhghoamapcdpbohphigoooaddinpkbai/4.19_0/* to  arbitrary dir. 
then open javascript/popup.js 60 line and replace
document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');
to
document.getElementById('menuTranslate').innerHTML += chrome.i18n.getMessage('translate');
and install it temporarily.
don't forget export your listings.

**Comment by bmg177** [comment]
Pardon me for not knowing exactly how to do this, I am not a coder. I have located the Extenstions/bhghoamapcdpbohphigoooaddinpkbai/4.19_0/ directory but I cannot find the popup.js file. Is it hidden? And, how do I edit the file one it is located?

Thank you

**Comment by bmg177** [comment]
Ah i see, I use notepad yes? I see the javascript folder but unable to locate popup.js

**Comment by mymindstorm** [comment]
It's under the javascript directory

**Comment by bmg177** [comment]
that directory is located here?
AppData\Local\Google\Chrome\User Data\Default\Extensions\bhghoamapcdpbohphigoooaddinpkbai\4.19_0\javascript

**Comment by adsactly** [comment]
OK we did this but there are a few newer ones that are not showing up for some reason. Is it possible this update destroyed some of our keys?

**Comment by mymindstorm** [comment]
The update only changed one line if code related to localization, it didn't touch storage.

**Comment by adsactly** [comment]
OK well, that is very strange because the newest OTP Codes are not showing up at all. but mostly all the other ones are showing.

**Comment by adsactly** [comment]
OK so the issue is still not fully resolved and ALL Codes are still safe even the ones we saved this past week?

**Comment by adsactly** [comment]
Please let us know and We will get down from the Tower and We won't JUMP.

**Comment by mymindstorm** [comment]
They should be ok

**Comment by bmg177** [comment]
editing the popup.js file and using that is telling me the extension is corrupted

I made a copy of the popup.js file and edited line 60 then swapped that file with the old one. Is there something else I have to do? Also, what does "dont forget to export your listings" mean

Thanks

**Comment by Alternating** [comment]
https://crx.dam.io/ext/bhghoamapcdpbohphigoooaddinpkbai.html  <<-- none of these will install.. All of these say "windows cannot open this file" also indicateds in chrome "failed to install"

**Comment by john19991** [comment]
Did anyone have success with the older version? Damn, this is crazy....Im losing patience now

**Comment by bmg177** [comment]
I can get version 4.18 working but I cant successfully get the updated popup.js file to work

**Comment by bmg177** [comment]
When this is fixed will it just automatically update the same way it automatically when you shit?

**Comment by ThePlenkov** [comment]
i changed the file but chrome loads cached version - cannot figure out what to do

**Comment by manib-kumar** [comment]
by when it'll get fixed?

**Comment by hartatyfatshaf** [comment]
OMG what should we doing now, please fix it soon.... 1 day 24 hour and more site can't access

**Comment by QuestUA** [comment]
jesus some brilliant hands did this shit...

**Comment by devdevan** [comment]
i did this "also you can copy Extenstions/bhghoamapcdpbohphigoooaddinpkbai/4.19_0/* to arbitrary dir.
then open javascript/popup.js 60 line and replace
document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');
to
document.getElementById('menuTranslate').innerHTML += chrome.i18n.getMessage('translate');
and install it temporarily."

succesfully goes to setting.
and now i think successfully lose my data because i cant export anything
just wait for update if u dont know what to do...

**Comment by ThePlenkov** [comment]
for me it's even worse - I cannot remember password.. Tried all my possible passwords but have this:

![image](https://user-images.githubusercontent.com/6381507/35486565-cd8f10c6-046f-11e8-8373-dcc9a42d3701.png)

**Comment by ThePlenkov** [comment]
there is no way to restore your password - so it's even more not secure than storing your tokens

**Comment by john19991** [comment]
Im not a technical person, so I do not really understand any of those codes, plus I not not want to waste time downloading worthless zip files....Please get this fixed immediately

**Comment by glukhovs** [comment]
Only 1 question. If there is only one line has been changed in the new version that messed everything up. WHY 12-24 to get it fixed?

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by reklaman** [comment]
I upgraded to version 4.20 and I have all my codes disappeared .... this is what such a joke.

**Comment by Sneezry** [comment]
@reklaman did you reinstall the extension?

**Comment by SimonDierckx** [comment]
Appreciate the effort to resolve this unfortunate error, thanks Sneezy

**Comment by adsactly** [comment]
All your Data is SAFE this is something I know for sure I found it in the Sync Extensions Settings folder in the Default Folder of my User Data folder for Chrome.

If you open the Log00003 file with Notepad++ you can see everything is still there its just really confusing to decode the codes and import them again.

You guys should make the Import / Export Feature to be a Text File that is saved and you can import text files etc.

**Comment by john19991** [comment]
Appreciate the work, @Sneezry Its working now

**Comment by bmg177** [comment]
My codes have disappeared, too. Is it because I removed the extension and reinstalled 4.20?

I still have the copy of the 4.19 folder, is there something in there I can used to retrieve the codes?

**Comment by bmg177** [comment]
Did I fuck myself by reinstalling?

**Comment by Sneezry** [comment]
@bmg177 Chrome will remove all your data if you uninstall the extension...

**Comment by bmg177** [comment]
Is there any way of retrieving it?

**Comment by Sneezry** [comment]
@bmg177 If you logged on any other computer, start it without internet connection, and you should see your data. Without internet connection is important, because Chrome will sync your data when it connects to the network, and the black data will overwrite your data.

**Comment by bmg177** [comment]
Ya looks like im fucked. Thats the only way?

**Comment by bmg177** [comment]
was able to restore the folder from previous version and got all but 1 auth code back. Thank god

**Comment by CryptoSavage** [comment]
So are we good yet? Will it automatically load up our existing codes we recently had on there?
Thank you.

**Comment by mymindstorm** [comment]
@CryptoSavage updating to version 4.20 will fix most issues

**Comment by CryptoSavage** [comment]
Well I am currently in version 4.20 and i believe I was yesterday when this was working as usual. Only up till this morning did my GA appear blank.

**Comment by mymindstorm** [comment]
If you go to "Import / Export" (don't copy that here) does the box show just `{}`? If not can you right click the extension page, click inspect, go to the console tab, and take a screenshot of that?

**Comment by reklaman** [comment]
I do not know what it is connected with but I had several accounts for Google, and when I logged in to one of them, some of the accounts I created earlier appeared, and the new ones did not appear. THE NAME I DO NOT ACCEPT AS THEIR RETURN MAY HELP THE RECOVERY OF THE SYSTEM.


Доброго времени суток.



С уважением Олег 8(029)9968210  , Stream Media

>Понедельник, 29 января 2018, 2:26 +03:00 от mymindstorm <notifications@github.com>:
>
>Если вы перейдете в «Импорт / Экспорт» (не копируйте это здесь), то в поле отображается только {}?  Если вы не можете щелкнуть правой кнопкой страницу расширения, нажмите «Проверить», перейдите на вкладку «Консоль» и сделайте снимок экрана?
>- 
>Вы получаете это, потому что вы были упомянуты. 
>Ответьте на это письмо прямо,  посмотрите на GitHub или  отключите тему .

**Comment by Saurabh995** [comment]
I am little bit confused. Do I need to reinstall or update something? Or
will it automatically get fixed when I open my browser?

**Comment by mymindstorm** [comment]
@Saurabh995 it will auto fix, but if you don't want to wait go to `chrome://extensions/`, check developer mode, and hit update extensions now in the top right.

![image](https://user-images.githubusercontent.com/27789806/35493632-85387bc2-047a-11e8-88ea-68a1e1f13c92.png)

**Comment by Saurabh995** [comment]
@mymindstorm Thanks a Ton!! Its working now. Made me realize the importance of backup!
