### ISSUE TITLE
Not working at all now :(

### ISSUE THREAD

**Issue by plasmageek** [Sneezry/authenticator#23]
Sorry to double spam you. I decided to remove my authenticators form my accounts via my old computer (which had this authenticator previously) and add them to my new computer. However, now whenever I try to add a new authenticator, none of the keys match. I've tried completely removing the app and re-adding it, and made sure that my other computer was shut down so the Chromes were cross-talking via sync. I tried both QR can and manually adding, and nothing is working.

**Comment by Sneezry** [comment]
Hi @plasmageek , could you tell me which website/service account meets the problem, and does it work correctly before?

**Comment by Sneezry** [comment]
BTW, try to run sync time with Google in the menu, I guess your local time is incorrect.

**Comment by plasmageek** [comment]
OK, so I tried syncing the clock and it gives the message "your local clock is too far off, please fix it before proceeding." What exactly does this mean? My computer is set to the local time?

**Comment by Sneezry** [comment]
That means your computer time is incorrect, you should sync your computer time with a time server.

发自我的 iPhone

在 2015年8月22日，下午10:13，plasmageek <notifications@github.com> 写道：

**Comment by plasmageek** [comment]
That fixed it, thanks :) Is it possible to use the authenticator between computers via the google sync btw?

**Comment by Sneezry** [comment]
Yes, Authenticator can work well between computers with Google sync.

发自我的 iPhone

在 2015年8月23日，上午1:18，plasmageek <notifications@github.com> 写道：
