### ISSUE TITLE
Password entry, Enter does not accept password (UX issue)

### ISSUE THREAD

**Issue by SparkDustJoe** [Sneezry/authenticator#24]
USABILITY, NOT FUNCTIONALITY

When entering the password for the encrypted Authenticator accounts, pressing Enter does nothing, you have to click Ok.  It would be faster when first unlocking Authenticator to enter the password and press enter, as would be the expected behavior, rather than be forced the extra click.  #firstworldproblems

**Comment by Sneezry** [comment]
Nice suggestion, thanks!

发自我的 iPhone

在 2015年8月23日，上午4:15，Dustin <notifications@github.com> 写道：

**Comment by Sneezry** [comment]
done in develop branch, and new version will be available soon.
