### ISSUE TITLE
Authenticator is not working - blank box 

### ISSUE THREAD

**Issue by HAVreeland** [Sneezry/authenticator#248]
Hi, 

I am trying to use the Google Authenticator for work when when I click the icon no numeric password pops up.  The settings and pencil are the only icons, but they are non-responsive as well.  

I restarted my computer, but the issue remains.  Please advise. 

Thanks, 

Heather V

**Comment by viktoriatereb** [comment]
и у меня такая же история.Что делать?

**Comment by iytd** [comment]
the same situation and what to do I do not know ...

**Comment by benannesley** [comment]
same with me it must be a general problem their end...thought I had been hacked

**Comment by pritamabc** [comment]
same prblem...help me

**Comment by Sneezry** [comment]
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Comment by benannesley** [comment]
im running 4.20...did as you said clicked on update extensions  and it made no difference  authenticator is blank when opened ...cant access any sites that needs it

**Comment by Sneezry** [comment]
@benannesley what can you see in the console of popup page? To see the log, open popup, right click the the page, select inspect, and switch to console in the new window.

**Comment by benannesley** [comment]
console is blank nothing in it
![console](https://user-images.githubusercontent.com/35901170/35487535-74b1359c-0474-11e8-8628-3dcb691df256.jpeg)

**Comment by benannesley** [comment]
not sure what you mean by pop up page

**Comment by benannesley** [comment]
but my guess is if we are all experiencing the same problem at the same time it must be something to do with a problem the authenticator end ..no?

**Comment by Sneezry** [comment]
@benannesley you did right. Now please paste code below:

```
chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))
```

can you see anything? If you can see the data, that's your secret, and DO NOT post it here.

**Comment by Sneezry** [comment]
@benannesley yeah, 4.19 has an issue to show codes, but it has no relationship with data, the issue won't break the data.

**Comment by benannesley** [comment]
dude no offense but im not going to add some unkown code onto my computer from an anonymous source
the authentication allows me access to some very important sites  ..u could be a hacker for all I know

**Comment by benannesley** [comment]
im using 4.20 anyway

**Comment by benannesley** [comment]
is someone else want to try it  from this thread be my guest

**Comment by samXsam89** [comment]
Hi guyz i have the exact same issue and i really need these codes for important access i'm so fucking scared right now. I don't have the codes to take 2FA authentification back.. :/

**Comment by Sneezry** [comment]
@benannesley I'm sorry about my fault to release 4.19 which causes the issue. Complain wont help, lets try to solve the problem.

If your data is lost on your computer, you still have couple of ways to try to find out your data:

1. If you have logged on any other computer, start it without network connection, and you should see your data on that computer
2. try to recover your account from the account provider

**Comment by Sneezry** [comment]
@samXsam89 do you upgrade the extension to 4.20? And NEVER REINSTALL the extension without a backup.

**Comment by samXsam89** [comment]
how do i upgrade it ?

**Comment by benannesley** [comment]
ok I did as yo
![code added](https://user-images.githubusercontent.com/35901170/35487833-2e506ed4-0478-11e8-9660-ed8ab00ce372.jpeg)
u asked and added the code this is what I got

**Comment by samXsam89** [comment]
(i haven't logged on any computer..and my data are lost on my computer for sure. I need a key to take back my 2FA keys and i don't have it anywhere. The only way for me to resolve that if you can't help me is to send emails to very support of websites and ask them to desactivate the 2FA, it will take a LOT of time and i need to connect to these websites several times a day..)

**Comment by benannesley** [comment]
this is crazy ...I have always used 4.20 ...what is going on ...a hack /....im in the same position as samxsam u only use 2FA for important sites which I need to get to urgently ...the only consolation Samxsam is that the sites will be getting a lot of people asking them to do the same thing

**Comment by Sneezry** [comment]
@samXsam89 I'm afraid you have to... Sorry about that... As you know, for security reason, it is impossible for me to save a copy of your secret

**Comment by Sneezry** [comment]
@benannesley did you see the empty data on the other computer without network connection as well? It is impossible

**Comment by samXsam89** [comment]
THANKS GOD it's okay i've done the upgrade to 4.20 and it works now

**Comment by samXsam89** [comment]
Thanks you @benannesley

**Comment by benannesley** [comment]
what did I do???

**Comment by Sneezry** [comment]
@benannesley please cool down, and answer my questions below to help you with your account recovery:

1. Do you have logged in any other computer with your account?
2. If so, did you try to start that computer WITHOUT network connection to find out your data?
3. If all solutions do not work for you, is it possible for you to seek help from your account provider?

**Comment by samXsam89** [comment]
sorry i meant thank you Sneezry !

**Comment by benannesley** [comment]
I have to go to the sites I use it for and and get a new back up key

**Comment by Sneezry** [comment]
@benannesley I'm sorry about the inconvenience I made, and it's a valuable lesson to me.
