### ISSUE TITLE
Is there any solution for this problem for now, is pass away now couple of hours and nothing resolved or some updates of possible time of resolving issues!!!

### ISSUE THREAD

**Issue by wolffuego** [Sneezry/authenticator#253]
Is there any solution for this problem for now, is pass away now couple of hours and nothing resolved or some updates of possible time of resolving issues!!!

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by dungeon9x123** [comment]
if authenticator fix . Can my key will restore ?
please help me ! i'm not backup ! i've 1.1 bitcoin on exchange please help me
@Sneezry

**Comment by vazquezvk** [comment]
the same problem in chrome, authenticator in white, I'm desperate help and thanks sneezry

**Comment by Sneezry** [comment]
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Comment by vazquezvk** [comment]
i love you men jajajajajajaja

**Comment by wolffuego** [comment]
tnx man , it's work, done it !!☺

**Comment by reklaman** [comment]
I upgraded to version 4.20 and all my codes disappeared help me get my account keys back

**Comment by Sneezry** [comment]
@reklaman If you reinstalled the extension, you have to find your data somewhere else.

If you logged on any other computer, start it without network connection, and your data should be there.

**Comment by reklaman** [comment]
I opened another computer and connected to the account and I had codes that were without an account, and the ones I needed were lost
