### ISSUE TITLE
WTF????

### ISSUE THREAD

**Issue by Birkofrulit** [Sneezry/authenticator#254]
![18955-clip-19kb 1](https://user-images.githubusercontent.com/35902129/35486974-566a22d6-0476-11e8-8d4b-08732757da2c.jpg)
where the fucking codes disappeared, how to pass the verification

**Comment by Sneezry** [comment]
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Comment by santaklouse** [comment]
I've already updated extension (https://goo.gl/YXYgoY) but it still not working
now another error: https://goo.gl/9mjVBh

**Comment by Sneezry** [comment]
@santaklouse please DO NOT UNINSTALL OR REINSTALL the extension in any cause, or your data will be lost. I'm checking your issue now.

**Comment by santaklouse** [comment]
great! =)

**Comment by santaklouse** [comment]
seems I have lost my keys. Please add to ext some backup functional =)

**Comment by bitnoah** [comment]
Hi  trying to solve the issue i have removed the extension and installed again, how do i recover my data then?

**Comment by Sneezry** [comment]
@bitnoah after you uninstalled the extension, all data will be removed by Google, and you cannot get it back. You need seek help from your account provider. I do not have any copy of your secrets. Sorry for that :-(

**Comment by bitnoah** [comment]
account provider, who then?

NOAH R. JUSTIN
CEO
BITCOINMONDE.COM

P.O. BOX 12 107 YAOUNDE, CAMEROON
Phone: +(237) 674 270 549

E-MAIL: rjnoah@sanagatechnologies.com <ncomputing@sanagatechnologies.com>
              bitnoah@bitcoinmonde.com

web site: www.bitcoinmonde.com <http://www.sanagatechnologies.com>,
*               toute l'info du bitcoin en Français!*


**********************POUR LE FRANCOPHONE*******************************

Mini-cours gratuit sur le bitcoin et autres crypto ici et maintenant:
http://miracledubitcoin.com/

Formation "Comment gagner de l'argent avec le bitcoin
<http://noahrjustin.1tpego.net/noahrjustin/le-miracle-du-bitcoin.php>".

**Comment by bitnoah** [comment]
who i need to contact please?

**Comment by Sneezry** [comment]
@bitnoah for example, if you use 2fa for bitfinex account, then you have to seek help from bitfinex to recover your account.

**Comment by ricashrq88** [comment]
hasta k por fin pya funciona,,,lo actualize la extension y ya me muestra los codigos...

**Comment by Sneezry** [comment]
@ricashrq88 sorry, I cannot read your language, could you please speak english? If your extension is 4.19, please upgrade it to 4.20 to see if the issue is resolved.

**Comment by santaklouse** [comment]
@Sneezry any way ext not works for me now. 
https://goo.gl/oXiJjp

**Comment by Sneezry** [comment]
@santaklouse can you see any data when run

```
chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))
```

in the console? If you can, backup anything you see. Do not post it here, the code contains your secrets.

**Comment by santaklouse** [comment]
@Sneezry unfortunately I see void

**Comment by santaklouse** [comment]
@Sneezry anyway thanks for your help.

**Comment by Sneezry** [comment]
@santaklouse what is the output? Just `{}` ?

**Comment by santaklouse** [comment]
@Sneezry yes

**Comment by Sneezry** [comment]
@santaklouse then it seems your data is lost on that computer, I'm sorry about it. If you have logged on any other computer, please try to find our your data by starting it WITHOUT network connection :-(

**Comment by santaklouse** [comment]
@Sneezry seems yes =( 
imho need to add some easy to use backup functionality because as I see many people lost money.
Thanks for help!

**Comment by santaklouse** [comment]
lost keys - lost money)

**Comment by mymindstorm** [comment]
Adding a message [like this](https://github.com/mymindstorm/authenticator/commit/dc815f826c3e07aee9759e9634f4c8237ddcee99#diff-f91f6f0a2ea2d1a98a57fa85b3672ba8R179) should help
