### ISSUE TITLE
Hay alguna solución para este problema por ahora, ya pasó un par de horas y no se resolvió nada o algunas actualizaciones de tiempo posible para resolver 

### ISSUE THREAD

**Issue by ricashrq88** [Sneezry/authenticator#255]

**Comment by ricashrq88** [comment]
Hay alguna solución para este problema por ahora, ya pasó un par de horas y no se resolvió nada o algunas actualizaciones de tiempo posible para resolver

**Comment by mymindstorm** [comment]
Go to `chrome://extensions` and do this
![image](https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png)
