### ISSUE TITLE
Still problem with authenticator ?

### ISSUE THREAD

**Issue by hagi999** [Sneezry/authenticator#256]
After update to 4.20 im still not see my codes. what i can do? 
please help

**Comment by aguero77** [comment]
Same here please quickly helppppppppp :(

**Comment by ricashrq88** [comment]
ESTOY EN LO MISMO ,,HASTA CUANTO MAS TENEMOS K SUFRIR CON ESTE PROBLEMA

**Comment by Sneezry** [comment]
@hagi999 did you reinstalled the extension?

**Comment by aguero77** [comment]
I didnt reinstalled

**Comment by hagi999** [comment]
i should reinstall ?

**Comment by khankarim45** [comment]
my authenticator blank sho pleas help me

**Comment by Sneezry** [comment]
@hagi999 NOOOOO! DO NOT REINSTALL the extension, or your data will be lost!

**Comment by aguero77** [comment]
I already didnt reinstall but still i cant see my data

**Comment by hagi999** [comment]
how to get backup database, step by step,

**Comment by miguel1111** [comment]
que problema con codigo 2fa

**Comment by miguel1111** [comment]
no puedo acceder a bitgrail

**Comment by Sneezry** [comment]
@hagi999 open chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/popup.html in your browser, right click anywhere in the page, click inspect, switch to console, paste code below:

`chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))`

all your data should be shown.

<img width="855" alt="qq20180129-053159 2x" src="https://user-images.githubusercontent.com/1621293/35487373-c0569ea6-04b5-11e8-9cfc-a6465195a5eb.png">

**Comment by digi1989** [comment]
@Sneezry should i be doing this also? 2fa still blank for me

"open chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/popup.html in your browser, right click anywhere in the page, click inspect, switch to console, paste code below:

chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))

all your data should be shown."

**Comment by aguero77** [comment]
same :(

**Comment by Sneezry** [comment]
@digi1989 please try it, and backup anything you see in the console. BTW, NEVER UNINSTALL OR REINSTALL the extension without a backup!

**Comment by aguero77** [comment]
when i copy paste it, it says undefined

**Comment by Sneezry** [comment]
@aguero77 did you reinstall or uninstall the extension before? All you data will be removed be Chrome then. If so, I'm afraid you have to recover your account from your account provider if you do not have a backup.

**Comment by hagi999** [comment]
![asdas](https://user-images.githubusercontent.com/35902595/35487477-4ee1aa42-047c-11e8-863c-46d7186f2ac5.png)

mate i did like u show but not working

**Comment by Sneezry** [comment]
@hagi999 did you reinstall or uninstall the extension before? All you data will be removed be Chrome then. If so, I'm afraid you have to recover your account from your account provider if you do not have a backup.

**Comment by aguero77** [comment]
i didnt reinstall. just click active/off . didnt reinstall or just like that ????

**Comment by aguero77** [comment]
Ok i will.

**Comment by hagi999** [comment]
so now, i have to wait 4 weeks to login into my work, because i have to wait on letter with recovery key, cheers for ur mistake .

**Comment by aguero77** [comment]
@Sneezry Tried it, doesnt work. You really hurts me. Cya

**Comment by Sneezry** [comment]
@hagi999 I'm very sorry about that :-(

Please always make a backup of the 2FA, for security reason, I cannot save any copy of your secrets, and when errors happen, the only one can help you is yourself, sorry again :-(

**Comment by Sneezry** [comment]
@aguero77 the only thing I can do is say sorry to you bro :-(

I'm so sorry I cannot help you to recover your account. Please always make a backup to use 2FA no matter which client you use.

**Comment by benannesley** [comment]
why is this happening to all these people at the same time it must be something to do with the authenticator developers and some problem their end

**Comment by digi1989** [comment]
![screenshot 2018-01-28 at 5 05 44 pm](https://user-images.githubusercontent.com/35900222/35487794-86f440c2-044d-11e8-8891-0c3492c6e770.png)

before i hit enter, should i do anything else here? You told me to back up anything that i see but i dont see anything @Sneezry

**Comment by Sneezry** [comment]
@digi1989 try to click background page and run the code in that console window

<img width="489" alt="b514c218-3432-46e0-a3c0-2daa5dcea1bf" src="https://user-images.githubusercontent.com/1621293/35487848-81330e8e-04bb-11e8-9862-eb00eb22c431.png">

**Comment by benannesley** [comment]
tried that as above.... same nothing

**Comment by digi1989** [comment]
@Sneezry doesnt look like i have that feature 
![screenshot 2018-01-28 at 5 22 13 pm](https://user-images.githubusercontent.com/35900222/35487959-dccd923a-044f-11e8-90b7-11e7aa426168.png)

**Comment by mymindstorm** [comment]
@digi1989 do this
![image](https://user-images.githubusercontent.com/27789806/35487967-8e8fa9f8-0447-11e8-82e9-bb74e8189626.png)

**Comment by digi1989** [comment]
@Sneezry  @mymindstorm  thank you very much guys. Also, i have one more question. Can u please show me how to backup my data so i never have to worry about losing anything ever again? Please and thank you

**Comment by mymindstorm** [comment]
@digi1989 open the "Import / Export" menu and copy it to somewhere safe. It's highly recommended to set a password in the security menu to encrypt your secrets before you put your secrets anywhere else.

**Comment by Sneezry** [comment]
@digi1989 When you enable 2FA with your account, you should see something on the web page like:

Backup this code for account recovery

And you should write down that code somewhere.

If you didn't write down the code when you enable 2FA, you should open Import / Export to backup anything you see in the box.

**Comment by digi1989** [comment]
@mymindstorm @Sneezry yup just created a passphrase. In the import/export  it says "update" at the bottom of it. Should i click on that first before copying and pasting all the code somewhere safe?

**Comment by Sneezry** [comment]
@mymindstorm Please make a backup of UNENCRYPTED version of your data.

1. Remove the passphrase before making backups. Open security menu, and leave passphrase empty, click OK
2. Open the Import / Export menu, copy all code you can see to anywhere safe
3. Set a passphrase again to encrypt your data

**Comment by digi1989** [comment]
@Sneezry  you posted to @mymindstorm . Was that supposed to be for me?

**Comment by Sneezry** [comment]
@digi1989 yeah, sorry for the mistake. It's 6:39 am in my location, and I'm working on this issue from about 4:00 am, please understand my mess

**Comment by mymindstorm** [comment]
Does making encrypted backups cause problems?

**Comment by digi1989** [comment]
@Sneezry  i understand. And for the record when i open up passphrase feature, its always empty to begin with. So im not sure if it remembers my password. But whenever i make a new one, it says "success". 
![screenshot 2018-01-28 at 5 42 00 pm](https://user-images.githubusercontent.com/35900222/35488193-92a4894a-0452-11e8-9676-6645d075138b.png)

**Comment by mymindstorm** [comment]
@digi1989 if you click ok while both are blank it removes your password iirc

**Comment by digi1989** [comment]
@mymindstorm aah ok. Going to do that now then

**Comment by Sneezry** [comment]
@mymindstorm I'm afraid users may forget the password when restore encrypted backups...

**Comment by digi1989** [comment]
@Sneezry @mymindstorm  Followed instructions. Have my passphrase and backup code in a safe place now. You guys have been a great help. Thank you very much

**Comment by benannesley** [comment]
HOW THE FUCK DID THIS HAPPEN... THIS IS GOING TO COST ME LOT OF FUCKINFG MONEY I WILL HAVE TO WAIT 7 DAYS TO GET ACCESS TO MY ACCOUNTS WTFFFFFFFFFFFF!!!!!!!!!!

**Comment by benannesley** [comment]
SNEEZRY WHAT THE FUCK DID U DO TO MAKE THESE ALL STOP WORKING AT THE SAME TIME ...UNBEALIVABLE

**Comment by mymindstorm** [comment]
@benannesley please calm down

**Comment by benannesley** [comment]
nothing i can do now but wait ...really annoyed this could  cost me a lot of lost money

**Comment by mymindstorm** [comment]
What version of the extension are you on?

**Comment by benannesley** [comment]
I have answered you 3 times 4.20

**Comment by benannesley** [comment]
I have lost all info and will need to reset through the site thats my only option

**Comment by benannesley** [comment]
6 differnet sites acatully .....WTF!!!!!!!!!!!!

**Comment by mymindstorm** [comment]
Oh, sorry. I assume you didn't take a backup then

**Comment by benannesley** [comment]
No ...but why did it fail in the first place ...u and your upgrade no doubt which u fucked up

**Comment by mymindstorm** [comment]
That wouldn't have caused you to lose your codes. If you reinstalled it, that would have caused you to lose your codes. If you happen to have another computer you might be able to get your codes from it before chrome sync kicks in

**Comment by benannesley** [comment]
this is a nightmare

**Comment by benannesley** [comment]
u have no idea?

**Comment by benannesley** [comment]
as far as not reinstalling that idiot sneezery should have made that clear before he typed anything else ...DO not re install...instead of waffling on about codes ...obviously not reinstalling is the main priority ...first thing he should have posted DO NOT REINSTALLL  how hard is that?????

**Comment by mymindstorm** [comment]
You should have been getting monthly notifications to backup your codes, plus the extension description warned you to backup too. Please watch your language.

**Comment by benannesley** [comment]
u watch your  language and never got a single notification  ...your incompetent  simple as that in terms of resolving this issue and why it happened in the first place

**Comment by benannesley** [comment]
pointless debate Im fuccked and that is that ....please be careful  with upgrades and I will make sure to back up all codes

**Comment by Sneezry** [comment]
@benannesley we will take more care for new release, it's all my fault this time, I do apologize.

**Comment by miguel1111** [comment]
que problema ahora sin poder acceder a bitgrail, confiando en esos codigos
2fa


2018-01-28 19:27 GMT-04:00 Zhe Li <notifications@github.com>:
