### ISSUE TITLE
My Authenticator is not working yet

### ISSUE THREAD

**Issue by swordfighter79** [Sneezry/authenticator#259]
I'm on window 7
using chrome
still have this
![capture_0006](https://user-images.githubusercontent.com/8459850/35488222-2b3ff0a4-0453-11e8-8b42-2beae4224e82.PNG)

thank you

**Comment by mymindstorm** [comment]
What version of the extension do you have? If you have 4.19: go to `chrome://extensions` check developer options in the top right and then hit the update extensions button that appears

**Comment by Sneezry** [comment]
Please upgrade to 4.20 to fix the issue.

DO NOT REINSTALL THE EXTENSION, OR YOUR DATA WILL BE LOST AND CAN NOT BE RECOVERED.

**Comment by Isco123** [comment]
Hi i am experiencing the same issue. It went blank and did not let me click the arrow or settings as it was unresponsive. So i removed from Chrome and reinstalled and this had 2FA codes for alot of my websites. Please advise ?

**Comment by swordfighter79** [comment]
Thank you every much that work 
thanks for working so hard on a sunday

It's greatly appreciated
thanks
