### ISSUE TITLE
I have remove the Authenticator and reinstall 

### ISSUE THREAD

**Issue by romeoog** [Sneezry/authenticator#260]
Hi, 

Anyway to recover my data?  I have many site I can't access without the authenticator.

Please help.

**Comment by mymindstorm** [comment]
Reinstalling clears the data apparently, if you have a backup you should restore that.

**Comment by romeoog** [comment]
sometimes theres a pop up asking to back up the data which I did, but I didn't manually back up any data didn't know how, so is there anything i can do?

**Comment by mymindstorm** [comment]
- If you have logged on any other computer, start it without internet, and you should see your data on that 
- try to recover your account from the account provider

**Comment by romeoog** [comment]
so log into my laptop it has the older version not working and i put it on plane mode so it doesn't have internet, but nothing is working, what can i try?

**Comment by mymindstorm** [comment]
Go to Import / Export and copy the data there to a safe place to backup. If you can't do that then right click the extension pop-up and hit 'Inspect', go to the console tab and run this command:
`chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))`

It should look something like this:
![image](https://user-images.githubusercontent.com/27789806/35488764-2d432b64-0453-11e8-8953-b0180361d230.png)

Copy the `{}` and everything in-between to a safe place, then paste it into the import export menu after updating.

**Comment by romeoog** [comment]
Version 4.19 doesn't let me go to option or do anything, I try with it on plane mode its doesn't work, do I have to turn on the internet?

**Comment by mymindstorm** [comment]
Go to `chrome://extensions` and click on background page
![image](https://user-images.githubusercontent.com/27789806/35488933-80485e7c-0455-11e8-8607-d171887dc754.png)
run this command:
`chrome.storage.sync.get(data=>console.log(JSON.stringify(data)))`

It should look something like this:
![image](https://user-images.githubusercontent.com/27789806/35488764-2d432b64-0453-11e8-8953-b0180361d230.png)

Copy the `{}` and everything in-between to a safe place, then paste it into the import export menu after updating.

**Comment by romeoog** [comment]
Tried on the laptop with internet off and nothing is working, any other options?

**Comment by mymindstorm** [comment]
If you have the backup data that I told you how to get then turn on internet and update the addon. After that go to "Import / Export" and paste the data you got with your secrets in.

**Comment by romeoog** [comment]
Try all that you recommend but I can't get the backup data, is it manually save somewhere?

**Comment by romeoog** [comment]
![image](https://user-images.githubusercontent.com/35904468/35489139-691d9b74-0458-11e8-82a0-39980ed87ffc.png)

Earlier I ran the command and just got that with internet off.

**Comment by mymindstorm** [comment]
So when you ran that command it returned `{}`?

**Comment by mymindstorm** [comment]
Your codes are gone and there isn't anything I can do to help you unless you have a backup.

**Comment by romeoog** [comment]
so im pretty much screwed, I can't logged into anything that I have turn on 2fa?

**Comment by mymindstorm** [comment]
Not completely, most websites let you open a support ticket to turn off 2FA

**Comment by romeoog** [comment]
I have a pc that I haven't log on for a while, I just turn on and I see it has my the codes so I think i might be saved, I let you know thanks.

**Comment by mymindstorm** [comment]
Good luck

**Comment by dginzbourg** [comment]
worked for me, thanks a lot

**Comment by romeoog** [comment]
mymindstorm well I got it restored but a few new one I have added is not on there, but from now on I will back it up everytime I add something new, thanks for all your help.
