### ISSUE TITLE
I have Reinstalled G Authenticator and it has reset everything. Is there any fix i have long 16 digit number that i note down but am not sure where i input this..Please help as i had alot of acc with 2FA? Thanks admin

### ISSUE THREAD

**Issue by Isco123** [Sneezry/authenticator#268]

**Comment by mymindstorm** [comment]
Reinstalling the add-on clears it's data. If you have a backup go to the `Import / Export` menu and paste that in. If you don't have a backup your codes are gone unless you installed the add-on onto another computer that hasn't synced the changes yet.

**Comment by Isco123** [comment]
Hi i manage to to find a 16 digit back up code for the account which was the most important, Then manually entered to add on authentication. Thank god cheers :)

**Comment by miguel1111** [comment]
isco 123 como le hicistes para obtener esa copia
gracias

**Comment by mymindstorm** [comment]
@miguel1111 no puedo hablar español

**Comment by miguel1111** [comment]
How do I get 2 Fa code to access my account?

**Comment by mymindstorm** [comment]
Need more information. Are codes gone? Or do you want to add new code?

**Comment by miguel1111** [comment]
I have a bitgrail account, and agg as 2fa security. first disappeared and then reintle the app and now I see the codes but I do not recognize the code page

**Comment by mymindstorm** [comment]
Reinstalling the add-on clears it's data. If you have a backup go to the Import / Export menu and paste that in. If you don't have a backup your codes are gone unless you installed the add-on onto another computer that hasn't synced the changes yet.

**Comment by miguel1111** [comment]
the problem is that I do not have backup, and for that reason I do not access my account error code
How would you help me solve this problem?

**Comment by mymindstorm** [comment]
I can't help you, but you can recover account. Start here: https://bitgrail.com/reset-2fa
