### ISSUE TITLE
Can't Delete Duplicate or Old 2FA Codes

### ISSUE THREAD

**Issue by adsactly** [Sneezry/authenticator#269]
When we try to delete the old 2FA Codes that we are no longer using it deletes ones that we are not clicking on for example. If we click to delete X it deletes Y which is Above or Below.

We think our codes are all messed up when we look at the Import/Export area we see that some of the codes are duplicated in names as well the "issuer" # 

Please help us troubleshoot this issue.

**Comment by mymindstorm** [comment]
Go into import / export and make sure the value that says `"index":` increments by one (starting at 0) and that it doesn't have any numbers that are the same. Then open and close the edit screen

**Comment by adsactly** [comment]
This is Mindfuck now some of our 2FA codes are invalid even tho all the codes are correct. we will try what you suggested above but this is really bad we can't access our exchanges or anything now :(

**Comment by adsactly** [comment]
OK That Fixed everything was little time consuming but you guys have built an incredible piece of software one suggestion for future upgrades is to make it possible to down a list of your keys in a human-readable format still encrypted like a CSV File etc.

**Comment by mymindstorm** [comment]
It's a lot easier to work with JSON files when you have something to format it with.

**Comment by adsactly** [comment]
OK so is it possible in the next release we can have a Downloadable file to import and export?

**Comment by mymindstorm** [comment]
That's something I was thinking about looking into adding, but it will probably take some time since the code needs to be refactored before anything big like that is added
