### ISSUE TITLE
Merge mymindstorm/Firefox into this repo

### ISSUE THREAD

**Issue by mymindstorm** [Sneezry/authenticator#270]
@Sneezry since you added me as a collaborator I'm going to move the Firefox and Crowdin service branches to this repo, is that ok with you?

**Comment by Sneezry** [comment]
It's not a good idea to move Firefox and Chrome into one repo, since different platforms may have different issues. I think we may create an org for this extension later, and create each repo for Chrome and Firefox.

**Comment by mymindstorm** [comment]
Good point, I can keep the feedback link pointing to the old repo so that doesn't happen if we do move the Firefox branch. The only reason I really wanted to do this is because Crowdin won't let me add more than one repo to sync, but the commit frequency isn't that much so syncing manually with upstream isn't that much of a pain.

**Comment by Sneezry** [comment]
We can add webhooks to handle sync issue

**Comment by mymindstorm** [comment]
Thanks for telling me about that, that makes my life a lot easier
