### ISSUE TITLE
me ostine llevo 3 dias y no eh podido entrar a mi cuenta de bitgrail, nose para que ponen seguridad con estos codigos y no tienen buen funcionamiento

### ISSUE THREAD

**Issue by miguel1111** [Sneezry/authenticator#271]

**Comment by mymindstorm** [comment]
I can't help you since you don't have a backup. You need to [contact Bigtrail yourself](https://bitgrail.com/reset-2fa) to recover your account.

**Comment by miguel1111** [comment]
como reactivo codigo 2fa para que me cuenta lo reconosca... ya que lo desactive y lo kiero volver a instalar , y creo que hice algo mal. ayuda

**Comment by mymindstorm** [comment]
You can install the extension again by going to [this link](https://chrome.google.com/webstore/detail/authenticator/bhghoamapcdpbohphigoooaddinpkbai). First, make sure you delete the old code that you deactivated by hitting the button in the top right and clicking the red minus on top of the old account. Then go to Bitgrail, enable 2fa, and finally add the code to authenticator again.

**Comment by mymindstorm** [comment]
Have you tried this? https://bitgrail.com/reset-2fa

**Comment by miguel1111** [comment]
si ya el soporte de bitgrail me desactivo 2fa y pude acceder a la cuenta, pero ahora para vender o cualquier cosa me pide que active de nuevo 2fa y activo la app y no me reconoce los codigos.

**Comment by miguel1111** [comment]
?

**Comment by miguel1111** [comment]
listo resolvi . gracias por el apoyo
