### ISSUE TITLE
The authenticator list is empty again

### ISSUE THREAD

**Issue by Github-Github-Github-Github** [Sneezry/authenticator#274]
It's been two days since my sheet is empty :(
What should i do?

Version 4.20

**Comment by mymindstorm** [comment]
If it's empty, you should try to restore a backup. Since you said it's empty again you probably have another chrome installation sending empty data via chrome sync.

**Comment by mymindstorm** [comment]
Go to the import export menu, if it just says `{}` your data is gone

**Comment by Github-Github-Github-Github** [comment]
I have only one windows account and also one google account

The import export menu is also empty :(
![capture](https://user-images.githubusercontent.com/36044787/35688775-5d8c2218-078b-11e8-983d-6c9455ae6180.JPG)

**Comment by mymindstorm** [comment]
There isn't much I can do to help you since you don't have a backup. Did you reinstall the extension? That clears it's data too.

**Comment by Github-Github-Github-Github** [comment]
Two days ago the windows suddenly crashed
and after reboot my authenticator list was gone

**Comment by Github-Github-Github-Github** [comment]
No, i did not reinstall anything

**Comment by mymindstorm** [comment]
I guess the windows crash is why you lost your data. You will need to recover the accounts you had codes enabled on by going through the accounts support site.
