### ISSUE TITLE
I need the history of my authenticator

### ISSUE THREAD

**Issue by alucardcsn** [Sneezry/authenticator#275]
I formatted the cell phone and registered another but not saved any authenticator already saved in the old cell phone, now I need to enter a "Game" account and it will not let me enter because it asks for authenticator and I have nothing saved, I need the saved history which have already been used. this is urgent

**Comment by mymindstorm** [comment]
This project isn't affiliated with the official Google authenticator Android / iOS app in any way. You'll need to contact their support for help.
