### ISSUE TITLE
I´m having problems with my Google Atenticathor

### ISSUE THREAD

**Issue by Gabrielcky** [Sneezry/authenticator#276]
I unistalled my app from my cell phone and i lost my code. How may i recover it again?

**Comment by mymindstorm** [comment]
This project isn't affiliated with the official Google authenticator Android / iOS app in any way. According to the listing on Google Play [here](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en) the support email for the official app is accounts-support@google.com.
