### ISSUE TITLE
hacked 2FA accounts 

### ISSUE THREAD

**Issue by benannesley** [Sneezry/authenticator#285]
Sneezery Just want you to know it looks like a lot of accounts have been hacked because of the mistake you made when you updated the 2FA... at least 7 illegal withdrawals of BTC from various accounts
mine included has taken place

**Comment by benannesley** [comment]
I think your app was hacked and when you updated it the hack started, thats is why we all lost our codes on the update ....do not update unless you have checked for a hack ...this is how they stole money from my kucoin account... they waited till it was unlocked and then stole all my BTC before support had told me it was unlocked ....very angry with  your response to the failed update ...you should have posted immediately do not reinstall the 2FA ...that was the only thing you needed to do to protect everyone but  you didn't you just tried to fix the problem, only when someone said should I reinstall the 2FA did you even mention not to ...very strange almost like you were part of the hack ...did you steal my BTC?

**Comment by mymindstorm** [comment]
That update was an accident and wouldn't cause you to get hacked. If you feel like insinuating claims like that feel free to look at the code and prove it, specifically commits 16e7309 which caused the issue and 6d894d0 which fixed the issue.

- Were your secrets encrypted? If they weren't anyone who has compromised your Google account would have your secrets. https://g.co/securitycheckup
- It's completely possible for someone with enough information about you to socially engineer their way into your account, bypassing the need for your codes
- Security comes at the cost of convenience, high value accounts should only have a place on your phone
- If you lost your codes you should have had a backup, as stated in a reminder that appears monthly and the extension description in all caps.

**Comment by benannesley** [comment]
you're so up yourself ...I said the 2FA was hacked .... then how do you explain that all the codes disappeared on the update and anyone who needed to get  there accounts unlocked because that idiot sneezery didn't bother to mention DONT REINSTALL THE 2FA  until it was too late... were hacked ... I know at least 7 kucoin accounts that were hacked by the same person using the same method .. he waited till they were unlocked and withdrew all the BTC before the account owner even knew they were unlocked ...get some balls and look more closely at your own security before it happens again and before you do another disastrous  update
