### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Cavain** [Sneezry/authenticator#294]
Hello,

Thank you for this best tool, I have a feature request about dragging 2-auth codes from up to down. e.g if i have 2 auth code added name ABC which shows in the top when i click on extension, so i wanted to move that down below to DEF and i want to move DEF on the top. I hope you understand it.

Thank you!

**Comment by Sneezry** [comment]
Do you mean if your list is like this before drag:

```
ABC
AAA
BBB
DEF
CCC
```

And after drag, it is like:

```
AAA
BBB
DEF
ABC
CCC
```

Do I understand correctly?

**Comment by Cavain** [comment]
Yes, that's correct.

**Comment by Sneezry** [comment]
The latest version (v5.0.6) works as you want. The latest version is still in public preview, and will be pushed to all users days later.

This project has moved to https://github.com/Authenticator-Extension/Authenticator, please open new issues there if you have any other question.
