### ISSUE TITLE
password require

### ISSUE THREAD

**Issue by dankac** [Sneezry/authenticator#297]
I 
![bez tytulu](https://user-images.githubusercontent.com/37746864/37869687-77fd8a3e-2fbc-11e8-9945-2112efb0b9a5.png)
have version 5.0.8 and authenticator asked me for password which i dont think i ever set up . Before i could just clik in on the icon and that app worked fine . Please help I have important passwords on it.

**Comment by mymindstorm** [comment]
We've moved to another repository, report here: Authenticator-Extension/Authenticator#100
