### ISSUE TITLE
Check if local time is too far off

### ISSUE THREAD

**Issue by multiwebinc** [Sneezry/authenticator#3]
I know a few people who were having problems with Google Authenticator and they didn't know why. The reason was that their device's clocks were too inaccurate and the tokens weren't validating.

I wrote a quick jQuery function that gets the server time from google.com and calculates the offset of the local computer. If the computer's clock is off by too much, it won't be able to validate the tokens, so I think it's a good idea to let the user know if this is the case.

    $.ajax({
		type: "HEAD",
		url: 'https://www.google.com',
		success: function(data, status, xhr) {
			var serverDate = new Date(xhr.getResponseHeader('Date'));
			var localDate = new Date();
			var timeDiff = Math.abs(serverDate.getTime() - localDate.getTime());

			if (timeDiff > 30000) {
				alert("Warning: Your computer's internal clock is off by more than 30 seconds. You should fix this before continuing.");
			}
		}
	});

It uses google.com, which almost everyone should have in their DNS cache, and only does a `HEAD` request, so it doesn't download the page content, and is asynchronous. Therefore it's pretty lightweight and won't interrupt anything else. You just need to add the following to your manifest file's permissions:

    "https://www.google.com/"

Of course, this just uses `alert()` to notify the user, but you could do many things with this, such as displaying a javascript pop-up, having some sort of bar that changes length and/or color based on the offset, adding a "troubleshooting" section which shows the actual offset, etc.

**Comment by Sneezry** [comment]
Done.

**Comment by multiwebinc** [comment]
Sorry for taking so long to reply. It might be a good idea to actually let the user know that their clock is too far off. Even though using an offset works, it's probably better to tell them to fix the underlying problem.

**Comment by Sneezry** [comment]
Yeah, you are right, I will fix this in the next version. BTW, I just make users be able to store passphrase in cookies, so the passphrase may be removed when the browser is closed and we do not need background page :-D

**Comment by multiwebinc** [comment]
Interesting. I didn't know you could do cookies with Chrome extensions. Good thinking.

**Comment by Sneezry** [comment]
Done in version 4.6
