### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by herombe301** [Sneezry/authenticator#31]

**Comment by herombe301** [comment]
xin code

**Comment by herombe301** [comment]
bạn ơi cho mình xin 1 cái code của tk gmail herombe301@gmail.com

**Comment by Sneezry** [comment]
Hi @herombe301 , I'd like to provide any help I can do for you, however, I can not understand your language, could you please describe your question in English or Chinese? Thanks.

Hi @herombe301 ，我愿意为你提供任何我可以提供的帮助，但我无法读懂你所使用的语言，你可以使用英语或者中文描述一下你的问题吗？谢谢。

**Comment by herombe301** [comment]
bạn ơi chát với mình được không làm ơn giúp lấy lại cái gmail đi tui xài thử mà khó xài quá giờ vô hoài không được

**Comment by herombe301** [comment]
My friends can not access their gmail accounts again it asked to confirm your web-party code it but his new wealth now lost just before trial

**Comment by Sneezry** [comment]
Hi @herombe301 , I'm sorry I still really understand your question. If your Gmail is locked and you can not get 2FA code with this extension as you forget your security password, you may seek help from Google(we can not help to recover your password as we never collect it). If you mean you'd like to check the code to make sure this extension is safe to use, you can download it as ZIP or clone it via Git, to clone it via Git, you need install a Git client or GitHub client. For windows, you may get it from windows.github.com, or mac from mac.github.com.

**Comment by Sneezry** [comment]
This issue has been closed as we didn't receive further feedback over a month.
