### ISSUE TITLE
Has this ever happened before?

### ISSUE THREAD

**Issue by joinmicah** [Sneezry/authenticator#36]
I entered my 2FA Code to Save it and now when I goto find it has been removed now I can't login to the system without the 2FA please help.

**Comment by Sneezry** [comment]
Hi @joinmicah , have you installed the extension on multiple computers and sync data among them?

**Comment by joinmicah** [comment]
I think that might be what happened... so is that last entry gone now?

To Our Success,
OWNER and Founder Of ADSactly.com
Micah J, Wallace
Home: 905-562-8211
Skype Me: ADSactly
Facebook Me: http://FB.com/micahjameswallace
Twitter: http://twitter.com/ADSactlyCrypto

[image: Micah Wallace on about.me]

Micah Wallace
about.me/micahwallace
  <http://about.me/micahwallace>

**Comment by Sneezry** [comment]
If you have removed that last entry on another machine and synced the data, then yes. Your data is stored in Google's server, and out of my control, so sorry about that.

You may contact with the service provider to get back your account. To avoid this happens again, you may take some actions: 1) sync your entry with your smart phone(move mouse to top right corner of the entry, and click the qr icon, scan it with Google Authenticator client installed on your smart phone), 2) backup your entry(click menu, export/import, copy all code in the box, and save it some safe place).

**Comment by joinmicah** [comment]
OK Thank You for the very fast reply.


To Our Success,
OWNER and Founder Of ADSactly.com
Micah J, Wallace
Home: 905-562-8211
Skype Me: ADSactly
Facebook Me: http://FB.com/micahjameswallace
Twitter: http://twitter.com/ADSactlyCrypto

[image: Micah Wallace on about.me]

Micah Wallace
about.me/micahwallace
  <http://about.me/micahwallace>
