### ISSUE TITLE
OTP No longer show

### ISSUE THREAD

**Issue by jasonamorrow** [Sneezry/authenticator#37]
Extension stopped showing OTPs and gives the following error:

Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.jsSHA.getHMAC (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/jssha-1.31.min.js:11:14553)
    at generate (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/totp.js:71:22)
    at updateCode (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:545:62)
    at Object.showCodes [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:678:9)
    at chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:66:21

**Comment by Sneezry** [comment]
Hi @jasonamorrow , does this issue happen after you add a new account?

**Comment by jasonamorrow** [comment]
I do not have a new account to add. I've deleted and manually added one account and the same problem occurs.

**Comment by Sneezry** [comment]
Please run script below in popup console, and paste the result here

for(var i=0;i<_secret.length;i++){var secret=_secret[i].secret;/^[a-z2-7]+=*$/.test(secret.toLowerCase())?console.log(_secret[i].account+": HEX"):/^[0-9a-f]+$/.test(secret.toLowerCase())?console.log(_secret[i].account+": BASE32"):/^bliz\-/.test(secret.toLowerCase())?console.log(_secret[i].account+": BLIZ"):/^blz\-/.test(secret.toLowerCase())?console.log(_secret[i].account+": BLIZ"):console.log(_secret[i].account+": ERROR")};

**Comment by jasonamorrow** [comment]
After completely removing all accounts and the extension. Re-adding the accounts, it has started working correctly.

**Comment by Sneezry** [comment]
I guess some secrets are broken. Any way, please remember to backup all your secrets =)
