### ISSUE TITLE
How to add B.net Authenticator?

### ISSUE THREAD

**Issue by Nihlum** [Sneezry/authenticator#38]
Hi!

I like this authenticator a lot, but I think I am too dumb to add the battle.net auth. I do not have a QR Code to scan and with manual entry Blizz uses a serial number and a recovery code. Both do not work to add it.
Would be glad if someone could help :)

Cheers!

**Comment by Sneezry** [comment]
Hi @Nihlum ,

You have to find out your battle.net auth secret before you add it to Authenticator. To find our your secret, install Python and run [this script](https://github.com/Sneezry/PyGetBlizSecret) (python getkey.py \<serial\> \<restore code\>). Then, enter the secret with blz- prefix when you add new account.

Why Authenticator doesn't support to add battle.net with serial and restore code directly?

For security reason, Authenticator blocks all web requests called by scripts within the extension (so your account data will not be sent to any one even your extension is hacked), exclude with Google server (to sync users' data). However, to find out battle.net secret, we need connect to blizzard's server.
