### ISSUE TITLE
MMMGlobal

### ISSUE THREAD

**Issue by maviaaman** [Sneezry/authenticator#39]

**Comment by Sneezry** [comment]
Hi @maviaaman, are you locked from your account? You are welcome to ask any question here.

**Comment by saingnhansath** [comment]
Hi Sneezry. I have used authenticator with my account mmmglobal. Accidentally the autheticator app become disappear from my computer. When I restore then I lose the code. Could you show me how to back up my code?

**Comment by Sneezry** [comment]
Hi @saingnhansath , have you removed the extension on other computer you signed in your Google account? BTW, it seems MMM is not a good thing.

**Comment by saingnhansath** [comment]
i use the same computer, but the authenticator just disappear from my popup.

**Comment by Tonghy** [comment]
I set up new window and i lose GA code now i can't login in MMMglobale website what should i do?

**Comment by pascalokoh** [comment]
up new window and i lose GA code now i can't login in MMMglobal website what should i do? And how to i recovery my code agian

**Comment by Sneezry** [comment]
The easiest way to recovery your code is contact with MMM. And to make a backup of your secrets is a good idea.
