### ISSUE TITLE
autenticator

### ISSUE THREAD

**Issue by Morenay** [Sneezry/authenticator#40]
Parou de gerar os códigos, não consigo resolver... :(

**Comment by Sneezry** [comment]
Hi @Morenay, could you please provide more details?

**Comment by Morenay** [comment]
O autenticador parou de gerar os 6 números (token) aparece o quadro em branco...

**Comment by Morenay** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/16450883/12013171/0c1dd54a-ad09-11e5-9a86-6c40a67e22c6.png)

**Comment by Sneezry** [comment]
@Morenay can you see any thing in export/import box? You may click menu icon (on top left corner of the popup window), export/import to open it.

Besides, have you removed the extension and reinstall it? Do you use this extension on a new computer?

**Comment by Morenay** [comment]
Na janela pop-up em exportação / importação aparece isso>>>>{ } depois bem embaixo aparece update eu clico aparece success e ok mas fica tudo na mesmo... já removi e reinstalei varias vezes o autenticator até formatei o computador, e nada... :(

**Comment by Sneezry** [comment]
So you installed the extension and reinstall it on your computer, right? After you remove the extension from Chrome, Google will remove its data as well, and I guess that's the reason why you data is lost. Did you backup your secret? If not, you need try to contact with your service provider to get back your account.

**Comment by Morenay** [comment]
Ok, isso é muito confuso para mim... mas vou tentar.Obrigado!

**Comment by Sneezry** [comment]
You are welcome :-)
