### ISSUE TITLE
Windows Domain Policy Usage (Not an Issue, just a query)

### ISSUE THREAD

**Issue by LukeSimms** [Sneezry/authenticator#41]
Hi,

I work as a IT Admin within a medium sized company who have just recently enforced the use of 2Fa (2 factor Authentication) for all users for gmail.

We stumble across this awesome application as we have some users who would rather not give their personal mobile number to Google.... I know there is always one.

So I was trying to deploy this awesome extension via Windows Group Policy but for this to work we need the update URL that should be in the manifest config file, which I looked at via this Git page and this entry is missing.

I just wanted to know if there is a update URL for this application for this purpose and for Chrome to know the update url path ? 

https://developer.chrome.com/extensions/autoupdate

Looking at the above Chrome uses this update URL to check for a new update, not sure how your applications updates are configured and I am now expert to software engineering. But if this is done differently then it would be awesome to know so that we can find another way around our issue.

Your help on this would be greatly appreciated :)

Kind Regards
Luke Simms

**Comment by Sneezry** [comment]
Hi @LukeSimms , extensions published on Google Web Store will be added https://clients2.google.com/service/update2/crx as update_url by Google automatically

**Comment by LukeSimms** [comment]
Hi Sneezry,

Thank you for your swift response, I in fact stumbled upon this advice about 10 minutes after posting this but I am very thankful that you replied with this advice anyways as I was lucky to find this advice online.

Kind Regards
Luke Simms
