### ISSUE TITLE
2-step Authentication Problem

### ISSUE THREAD

**Issue by amyestep** [Sneezry/authenticator#43]
I recently installed 2014 Sneezry 2-factor Authenticator and had one program requiring a verification code to log-in. I accidentally deleted the program/website from the authenticator so am no longer receiving verification codes. However, the website still says I am registered for a 2-factor authentication, requiring a verification code. This means I cannot log into this website and it is extremely important that I can access it. I have tried adding the website back to the system but I don't have the QR code needed. What do I do?

**Comment by multiwebinc** [comment]
Without the secret key from the QR code or a backup of your accounts it would be impossible to regain access. You will have to contact the site admins and have them remove your 2 factor authentication.

**Comment by multiwebinc** [comment]
This extension needs a delete account confirmation. It is far too easy to accidentally delete your accounts.

**Comment by amyestep** [comment]
Thank you, and I agree. I will continue to try and contact the site
administrators.
