### ISSUE TITLE
Data doesn't sync

### ISSUE THREAD

**Issue by mrchief** [Sneezry/authenticator#44]
I'm signed in to google but the data doesn't sync between my office and home computer. I have 6-7 codes on office computer but only 1 on home computer.

**Comment by Sneezry** [comment]
You may copy your code from settings->export/import, then paste it into your home computer

**Comment by mrchief** [comment]
Yeah but I was looking for an extension that would do this for me. Anyway, thanks!

**Comment by Sneezry** [comment]
Hi @mrchief , you are right, the extension should sync data itself, and in fact, it does so. The extension sync data with Google built in service, if your data is not synced, you just need wait, however, if you'd like to sync data immediately, you have to copy the code by yourself :-)

**Comment by mrchief** [comment]
How long do I have to wait? Its been few weeks since I started using it. What I'm suggesting is that there is a bug/issue/problem with whatever sync mechanism you're relying on. Its not working.

**Comment by Sneezry** [comment]
It depends on Google, however, it shouldn't be longer than one or two days. Please check your connection to Google and whether you've signed with the same account between your home computer and office computer.
