### ISSUE TITLE
[FEATURE] Generate a QR Code for an entry?

### ISSUE THREAD

**Issue by kalbasit** [Sneezry/authenticator#45]
I would love to be able to generate a QR Code out of an entry to be able to scan it in a different Authenticator (say Google Authenticator on iOS or Android).

**Comment by Sneezry** [comment]
Hi @kalbasit , have you trid to click the qr icon at top right corner of the entry? Move your mouse there, and you will see that icon.

**Comment by kalbasit** [comment]
:flushed:

Thanks @Sneezry that worked perfectly.
