### ISSUE TITLE
Issue in chrome.storage.sync.get

### ISSUE THREAD

**Issue by preraksola** [Sneezry/authenticator#46]
Hi,
I recently downloaded your source code and tried to run it locally on my browser as an unpacked extension. I was testing the extension with some random account names and secrets.
For first entry it worked well, but for any other entries after that, it shows **`......`** instead of the otp.

When I looked at the console , it said 
> Error in response to storage.get: TypeError: Cannot read property 'length' of undefined

at the line 
> chrome.storage.sync.get

Is there any way that I can avoid this, or is it because I am inserting some random data?

Thank you
Prerak

**Comment by Sneezry** [comment]
Hi @preraksola , could you please tell me what secret leads the error?

**Comment by preraksola** [comment]
The data was:

Account: Test
Secret: test1234
Tye: Time Based

**Comment by Sneezry** [comment]
Your secret is invalid, a valid secret is in Base32 format, you may learn more about Base32 here: https://en.wikipedia.org/wiki/Base32

For your case, 1 shouldn't be in your secret.

**Comment by preraksola** [comment]
Okay. Thank you for the information. I didn't knew that... :+1: 

There is one more thing, that I am having issue with. Every time I open the extension, it says
> Caution! Your local clock is too far off, please fix it before continuing.

My current location is **Paris, France (GMT +1:00)** so I changed the URL to `www.google.fr` thinking the time for `www.google.com` might be the current time in USA. But still it's showing me the above error. My clock is synced with the internet time so I can assure that it's showing the right time.

So, is there anything else that I need to do?

**Comment by Sneezry** [comment]
Your local clock now is 2016/02/05 11:30, right?

**Comment by preraksola** [comment]
Yes

**Comment by Sneezry** [comment]
Then please check date on your computer. The extension check clock based on UTC time, but not your local time.

**Comment by Sneezry** [comment]
![Google UTC/GMT](https://cloud.githubusercontent.com/assets/1621293/12843852/ffab7cc0-cc36-11e5-8afb-ad60c12a7b7a.png)

**Comment by preraksola** [comment]
The date is correct on my computer. These are the things that I have currently:

> Time from google.com header: 10:52 GMT
> Exact current time: 11:52
> My computer Time: 11:46 (Lag of 6 minutes)

The extension shows alert for a difference of more 5 minutes. So is it because my computer's time  is lagging by 6 minutes from the exact current time or is it because of the GMT difference?

**Comment by Sneezry** [comment]
Because your computer's time is lagging by 6 minutes, there's no error caused by GMT :-)

**Comment by preraksola** [comment]
Okay. I'll fix that.

Sorry, but I have one more query.
One of the messages in your `messages.json` file says that extension can accept **Base32** and **HEX** strings as secret.
So, I tried with the following data:
> Account: testHex
> Secret: 0x1234abc
> Type: Time based

But still, it was not able to generate the OTP.
So, is there place where I am wrong, or it can only accept Base32 string as secret?

**Comment by Sneezry** [comment]
Try to remove 0x, and it will work :-)

**Comment by preraksola** [comment]
Okay, so a secret like `123abc` can be considered for both the formats?

**Comment by Sneezry** [comment]
The extension may check whether the secret is base32, if not, it will try to regard as hex.

**Comment by preraksola** [comment]
Okay. Thank you for the information and help... :+1:  :)
I have modified the source code a bit for a check after the `secret` input. If you think it's good enough, you can merge the pull  request.

Thank you once again.
Prerak
