### ISSUE TITLE
Can somebody help me with 2FA, I blocked 1 of my accounts...

### ISSUE THREAD

**Issue by Megmog** [Sneezry/authenticator#5]
I had synced 2FA app on Chrome because it doesnt work on my phone I dont know why. Then I turned off 2FA now, I have turned on and I cannot use my 2FA again at all............. what to do ? I contact the support but they dont respond soon maybe until 24-48 hours. Is there any chance to sync my account. The app is added on my chrome and it was working well. But now doesnt.

**Comment by Sneezry** [comment]
Hi, Megmog

I can't catch up with your point, can you answer these questions with yes or no

1. You have installed this Chrome extension because your phone can not work?
2. You had synced 2FA app on Chrome, so you had installed this extension on more then one computers?
3. You turned off 2FA and then turned on again?
4. You can not sign in your account because you have lost your 2FA secret?

Please tell me your answers, and I'll think about how to help you.

Li Zhe

**Comment by Sneezry** [comment]
Hi, Megmog

I will close this issue in 2 days if you fail to respond in time.

Li Zhe

**Comment by Megmog** [comment]
Oh, sorry Li Zhe. but I have no idea waht I did. I talked with website
admins adn they removed me the 2FA. Anyway now I have 2FA on my Windows 7
Chrome Brower. On my android my 2FA application do not work. I have no idea
why is it like that. I tried to synchronized but it doesnt work. It says me
that synchronization seems like to be already done before. I have tried to
installed many times. I reinstall android and updated everythign. It is the
same. It never works on my android.

**Comment by Megmog** [comment]
My first problem was when I turned off 2FA from account security settings
and then I turned on. After these 2 operations 2FA on my Chrome browsers on
windows 7 didnt work anymore and wasnt able to be synchorinzed. But I
resolved that problem. Now my problem is if it is possible to install it
and make it work properly on my tablet android.

On Tue, Apr 7, 2015 at 1:28 PM, Petroslav Panayotov <theredblack13@gmail.com
> wrote:

> Oh, sorry Li Zhe. but I have no idea waht I did. I talked with website
> admins adn they removed me the 2FA. Anyway now I have 2FA on my Windows 7
> Chrome Brower. On my android my 2FA application do not work. I have no idea
> why is it like that. I tried to synchronized but it doesnt work. It says me
> that synchronization seems like to be already done before. I have tried to
> installed many times. I reinstall android and updated everythign. It is the
> same. It never works on my android.
>

**Comment by Sneezry** [comment]
OK Megmog, I'm happy to know you have solved the problem with you account. To the android issue, it's beyond my ability, so would you mind me close this issue, or do you have any other questions about the extension?

Li Zhe

**Comment by Megmog** [comment]
Its ok , Li. Close it. Whatever. Just say me if it was possible to
synchronize it again after I had reset 2FA account security settings.

**Comment by Sneezry** [comment]
Account data will be synced by Google among extensions. You may also open QR code and scan it with your smart phone.

![](https://cloud.githubusercontent.com/assets/1621293/7022557/c642b65e-dd5f-11e4-9251-04224b04131d.png)
![](https://cloud.githubusercontent.com/assets/1621293/7022556/c64216ae-dd5f-11e4-9f44-d4496e061179.png)
