### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by bkolada** [Sneezry/authenticator#6]
Hey, @Sneezry you wrote great app, since I started writing some 2fa in django it makes a lot easier to test couple of things. 

Now I have some thoughts about that: 
1. I think each row with token should contain username - google authenticator mobile app contains 
2. Maybe some autofill input field with token name
3. [BUG] After removing elements on list I want to add new element without clicking pencil it doesn't remove anything just adds new entry 
4. Usually we have one token on screen maybe read entire webpage and analyse token 

Anyway, great job, great extension!
Bart

**Comment by Sneezry** [comment]
Hi @bkolada 

Thank you for your suggestions. Now we have trouble in releasing new version for 4.4 is still in pending review status for 12 days, we have to wait to release new version till Google pass the current version review.

I will fix the bug in the later version :-)

Li Zhe

**Comment by Sneezry** [comment]
bug fixed in version 4.5
