### ISSUE TITLE
QR scan not working for local images or html pages

### ISSUE THREAD

**Issue by martinfthomsen** [Sneezry/authenticator#66]
Hi Sneezry,
When trying to scan the QR code from a local image or a simple html page containing the image, I get the following error (and the instructions do not help...):
<b><i>Capture failed, please reload page you are viewing and try again</i></b>

I hope you can fix this.

Best, M

**Comment by preraksola** [comment]
In your extensions page (chrome://extensions/) click on `Allow access to file URLs` checkbox.

![screenshot from 2016-05-30 14 21 34](https://cloud.githubusercontent.com/assets/8655814/15649516/66d8c7dc-2672-11e6-86b7-dd2d72e7b1d2.png)

**Comment by martinfthomsen** [comment]
Thank you, that fixed it.
