### ISSUE TITLE
Bantuan

### ISSUE THREAD

**Issue by kusuma68** [Sneezry/authenticator#67]
Saya telah memindai Google Authenticator untuk scurity login pada suatu web. Entah karena terhapus atau apa, yang jelas dalam daftar Authenticator yang pernah saya buat hilang. sampai saat ini hampir 2 bulan saya tidak bisa login di web tersebut. 
Pertanyaan:
1. Bagaimana cara memulihkan kembali Authenticator pada login web yang hilang.
2. Bagaimana alternatif untuk me reset ulang Google Authenticator agar tidak aktif lagi di login web tersebut.
Nama Web (situs) https://hashocean.com (sebuah situs investasi Bitcoin)

**Comment by Sneezry** [comment]
Hi kusuma,

You need contact with support@hashocean.com to remove 2FA from your account.

No one can help you to recover missing secret code, please backup your data.
