### ISSUE TITLE
Q/R export? useful to sync with other apps

### ISSUE THREAD

**Issue by geeohgeegeeoh** [Sneezry/authenticator#69]
I find every time I re-upgrade my Androids I lose google auth state. The Q/R code import path requires me to unlock a set of secure doc images (1password) to get screenview of the Q/R to re-import.

IF you include valid Q/R initiators alongside the json text, we can pull up the import/export, and scan them off the screen. Resync will be much simpler.

**Comment by Sneezry** [comment]
Just move mouse to top right corner of the entry, and you'll see a QR icon, then click it :-)

**Comment by geeohgeegeeoh** [comment]
colour me stupid! I think having the icon only appear on hover was too clever for me! thanks. close request.
