### ISSUE TITLE
Clock dont run!

### ISSUE THREAD

**Issue by RicardoUtreras** [Sneezry/authenticator#71]
The clock does not advance but after a moment the key changes . The key works sometimes and sometimes not.
The reinstallation solves the problem , but I have 500 users so it is not a viable solution.

**Comment by RicardoUtreras** [comment]
Any idea?

**Comment by RicardoUtreras** [comment]
The uninstall and reinstall solve the problem.

**Comment by Sneezry** [comment]
Reinstall may destroy all your data, remember to backup your data.
