### ISSUE TITLE
Unrecognition qrcode

### ISSUE THREAD

**Issue by gbywt** [Sneezry/authenticator#8]
Why this always happen? something got? something not?
Both qrcode are same and scan it. Result is different

**Comment by Sneezry** [comment]
Hi gbywt,

We use jsqrcode(https://github.com/LazarSoft/jsqrcode) to read qr code, so I guess this issue should be theirs. Please try one more time when the scanning fails. Sorry about that.

Li Zhe

**Comment by gbywt** [comment]
Is that support to read OTP qrcode?

**Comment by Sneezry** [comment]
@gbywt sure, OTP qrcode is not any much special.

**Comment by multiwebinc** [comment]
Maybe the QR code is actually invalid. Try going to http://zxing.org/w/decode.jspx and decode the QR code. It should have the following format:

    otpauth://totp/YourAccountName?secret=hf3wvusfct7p6x4lahp3qse4es3j4q3y

**Comment by Sneezry** [comment]
I guess you misunderstand it. QR code can encode any text, so if you may get the text by decoding it, then it's an invalid QR code. I'm sure the problem belongs with jsqrcode, as other people had submitted similar issues that the lib failed to decode some QR codes.

**Comment by gbywt** [comment]
If can, can your make a new window ( or window popout) to show the information inside QR code when you scan.

**Comment by Sneezry** [comment]
@gbywt yeah, we have done it.

![](https://cloud.githubusercontent.com/assets/1621293/7225473/850efec4-e771-11e4-8e12-23f3c8a3a4a1.png)

**Comment by gbywt** [comment]
One more bug. When you click on the button "scan QR code" , it will show a guideline for select a QR code image , like this 
![image](https://cloud.githubusercontent.com/assets/9497778/7226889/23d4f7f4-e77f-11e4-92e4-bf66138c7348.png)
(right?). But sometime it do not respond on it (mean not show guideline)
like this 
![image](https://cloud.githubusercontent.com/assets/9497778/7226903/4036c594-e77f-11e4-82f7-17afc781e2a3.png)
.

**Comment by Sneezry** [comment]
Do you mean sometimes when you click Scan QR Code but nothing happens?

[Chinese]
你是说有的时候点击扫描QR码，但却什么也没有发生吗？

**Comment by gbywt** [comment]
yup ....

**Comment by multiwebinc** [comment]
I remember that happening as well. It is because the page was loaded before the extension was installed or while it was disabled.

Steps to reproduce:

1) Disable Authenticator extension
2) Navigate to any page
3) Enable the extension
4) Go back to the page (without refreshing) and try to scan the page

Is there a way to detect whether the extension actually has access to a page, and if not, show a warning message to get the user to refresh it?

**Comment by Sneezry** [comment]
@multiwebinc yes we can, an update will follow soon to add this feature.

**Comment by Sneezry** [comment]
Done in v4.8

![](https://cloud.githubusercontent.com/assets/1621293/7244045/042e20ae-e808-11e4-911b-331edd3b5cb1.png)

**Comment by multiwebinc** [comment]
That was fast!

**Comment by Sneezry** [comment]
@multiwebinc ;-)

**Comment by gbywt** [comment]
update very fast !!! nice
