### ISSUE TITLE
GOOGLE AUTHENTICATOR

### ISSUE THREAD

**Issue by katidyd1** [Sneezry/authenticator#80]
I am attempting to use my google authenticator to enter the ARCH system with my new employer.

When I click on the authenticator at the top of my screen it does not generate a number.  When I highlight the scan image on the page, I receive an error message stating that the QR thingy is not recognized.

It says I have to set up or register for this authenticator on my mobile device, but I have downloaded it to my computer.  How can I register my authenticator on the PC?  I cannot complete my charts or even enter my hours for each day.  It is really important for a new hire.  Any help would be appreciated. Thanks.

**Comment by Sneezry** [comment]
You may add account by Manual Entry if Scan QR Code doesn't work.

**Comment by katidyd1** [comment]
Where are the instructions for Manual Entry on this site...or in google, please?

**Comment by Sneezry** [comment]
You should see a secret on the same page of QR. Here's an instruction on YouTube https://www.youtube.com/watch?v=hMnsOVE-Ipo

**Comment by katidyd1** [comment]
Thank you so much!  

Even though the entire video was in Polish or Czech language, I was able to figure it out and I am now able to sign into my ARCH program.

Again, I greatly appreciate your help.  // Kate


Kate Almas, CCS-P | AHIMA Certified 2001Data Integrity Specialist & Remote Coder-ReviewerProvider Education & Resident Training ConsultantCode Based Reimbursement & Facility CDM Analyst[ O ] 904-269-5343[ C ]  904-673-4704"There are two kinds of people: Those who do the work, and those who take the credit. Try to be in the first group; there is less competition there."
~   Indira Gandhi    ~ Date: Wed, 27 Jul 2016 08:48:30 -0700
