### ISSUE TITLE
Lost all accounts

### ISSUE THREAD

**Issue by darkearner** [Sneezry/authenticator#87]
Hello i had more than 5 accounts and using it from more than years.when  i signed up via my gmail it autmaticaly detects my all accounts.I know my paraphase security key.
But last night i removed the authenticator extenision app from Chrome and i was already logged in to my gamil .now i logged out and again  sign in to my gmail acc but my accounts are not comming m very tensed please help me .

**Comment by darkearner** [comment]
Please i dont have all of the security keys of those account

**Comment by Sneezry** [comment]
Sorry, I cannot help you. Your data has been destroyed both on your local machine and Google server when you remove the extension. I suggest you recover your data if you have a backup, or seek help from your account support.
