### ISSUE TITLE
What's the easiest way to decrypt my secret keys?

### ISSUE THREAD

**Issue by paradocks** [Sneezry/authenticator#88]
I have the password, but I need to decrypt the secret keys because I need to import them to another device. There is no option in the extension to remove the password from the keys.

**Comment by Sneezry** [comment]
Just set password to empty. You needn't remove password, if you want to
import to Chrome, just import the encrypted data, and the extension will
ask you to enter password, if you want to import to mobile, move mouse to
top left of the entry, then click the qr icon to show qr code to import
data.

2016年10月14日 上午4:56，"paradocks" <notifications@github.com>写道：

**Comment by paradocks** [comment]
Thanks I don't know why I didn't try that in the first place lol. I never noticed the QR button either. Thanks again for the help!
