### ISSUE TITLE
I will improve Scan QR function in later version

### ISSUE THREAD

**Issue by Sneezry** [Sneezry/authenticator#9]
jsqrcode works well at most of time, however, it fails in decoding sometimes. I will improve the lib in later version.

Maybe we need some computer vision knowledge.

**Comment by Sneezry** [comment]
I have solved https://github.com/LazarSoft/jsqrcode/issues/41, however, I still need more images to test. Please post any qr code we failed to decode.

![](https://cloud.githubusercontent.com/assets/1621293/7298310/3cf6d4a8-ea01-11e4-9d03-f37775dfae6a.png)

**Comment by bkalar09** [comment]
I have several codes that AWS produces that can't be scanned.
![image](https://cloud.githubusercontent.com/assets/12201478/7433856/658335bc-efea-11e4-9498-84f5073d4b3d.png)

**Comment by bkalar09** [comment]
Another that wont scan.
![image](https://cloud.githubusercontent.com/assets/12201478/7433879/aa7d3064-efea-11e4-968d-51f65b82cf84.png)

**Comment by Sneezry** [comment]
Hi @bkalar09 

Which version extension do you use? I can scan both of them with version 4.13

![](https://cloud.githubusercontent.com/assets/1621293/7434505/db8bb440-f06d-11e4-947f-5ce8c7eb0912.png)
![](https://cloud.githubusercontent.com/assets/1621293/7434506/db8ee200-f06d-11e4-869f-c574b227e307.png)

**Comment by bkalar09** [comment]
4.1.3

**Comment by Sneezry** [comment]
Strange :-S

I have tested several times, and it works all the time~

**Comment by bkalar09** [comment]
I'm working on a screen shot of it in action

**Comment by Sneezry** [comment]
I guess I know the problem is... Is your display a retina one or do you zoom in or out your browser?

**Comment by bkalar09** [comment]
Here it is.
![image](https://cloud.githubusercontent.com/assets/12201478/7435057/ebc4c4ec-eff4-11e4-9d1b-9da56244f3ee.png)

**Comment by bkalar09** [comment]
I am using a ThinkVision Pro 2940m.  I don't zoom either.

**Comment by bkalar09** [comment]
My chrome version is Version "42.0.2311.135 m".  The window I am using is "pinned" to the right side of the monitor.  I am only using half of the screen for this instance of chrome.

**Comment by bkalar09** [comment]
My resolution is 3840 x 2160.

**Comment by Sneezry** [comment]
OK, I think I know how to solve your issue, we fail to locate the qr code under some retina displays.

![qr](https://cloud.githubusercontent.com/assets/1621293/7435170/db693cfc-f073-11e4-864e-b4aa146866ff.png)

I'm working on this now, please wait for a moment before I solve this :-)

Thanks for your feedback

**Comment by Sneezry** [comment]
@bkalar09 version 4.14 now is available in web store, please update your extension and feedback further, thanks :-)

**Comment by multiwebinc** [comment]
@Sneezry For some reason it's not updating for me yet, however I am having the same problem with 4.13 if I scan *twice*. It works the first time but not the second time it doesn't scan correctly. It doesn't even draw the box on the screen when I drag the mouse.

**Comment by bkalar09** [comment]
That worked.  Thanks

**Comment by multiwebinc** [comment]
It finally updated for me, but I still have the same problem.

**Comment by multiwebinc** [comment]
Here's a screencast of what I mean: http://youtu.be/qvz8_n16Qas

I don't know how to make the resolution higher on Youtube, sorry for the bad quality. 

Here's the original file (2MB) in case you want it: http://www.filedropper.com/out-1

**Comment by Sneezry** [comment]
@multiwebinc I watched the video, and I understand the problem you meet.

I think that is another issue about mouse event listening, I have created a new issue(https://github.com/Sneezry/authenticator/issues/14) to track it.

**Comment by Sneezry** [comment]
Scan QR works fine now.
