### ISSUE TITLE
I Can not Use Authenticator

### ISSUE THREAD

**Issue by Garintz** [Sneezry/authenticator#90]
caution your local clock is too far off, please fix it before continuing
Please instructions

**Comment by Sneezry** [comment]
Your computer clock is incorrect, sync it with Internet time.

**Comment by Garintz** [comment]
how to make

**Comment by Sneezry** [comment]
https://www.google.com.sg/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=how+to+sync+computer+time+with+internet

**Comment by Garintz** [comment]
Ok thanks
